### ISSUE TITLE
Lorebook Item

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroQuest#102]
Extend vanilla books. Read book content from a ~~JSON~~ text format.  ~~Allow other mods to register books via an API~~.

Type:
- civilization lore (collectable sets of 12) (explanations of the civs and negative effects they can cause)
- location hints (location to lost artifact or possibly even structure or nearby resources)
- game hints (includes books from other mods)
- general fiction (random poems / lore / etc)

https://github.com/ToroCraft/ToroQuest/issues/97

**Comment by CawCawDrakon** [comment]
The first lorebook: A Pantheon Unbiased, Book I
Pantheon Unbiased is a series of 9 to 12 common books in which the gods and other divine beings are described from a neutral, non-civ viewpoint.
[A Pantheon Unbiased.zip](https://github.com/ToroCraft/ToroQuest/files/732612/A.Pantheon.Unbiased.zip)

**Comment by frodare** [comment]
@CawCawDrakon The books will need to be saved as text files. The current format uses the first line as the title, the second as the author and the rest of the lines as the content of the book.  Double returned lines will create a new page.  If you are still interested in contributing to this project, what I would like you to do is fork this repo and then add some of the book files.  That way you will show up as contributor to the project.  That will also give you the ability to edit the books directly in the code base. Once you fork the repo and add the book files, you can create a pull request.  Let me know if you have any questions or are not familiar with github and want some pointers.

Book files go in:
https://github.com/ToroCraft/ToroQuest/blob/master/resources/assets/toroquest/books/*

There is currently one example book: https://github.com/ToroCraft/ToroQuest/blob/master/resources/assets/toroquest/books/civ_lore/test.txt

**Comment by CawCawDrakon** [comment]
Ah, thanks! Yes, I´m not that experienced with github (aka I just signed up four weeks ago and didn´t do much), so some pointers would be helpful. For example, did I create that book right?

**Comment by frodare** [comment]
Yes, looks like you got it :)  I just left a comment about changing the file name, after that I will merge it into the code base.

**Comment by frodare** [comment]
I decided to leave off API support for now.
