### ISSUE TITLE
Toro Is Weak

### ISSUE THREAD

**Issue by kenijey** [ToroCraft/ToroQuest#105]
Toro is very weak... low damage, low hp... okay i know that you don't have to make it much stronger, but at least you can add health multiplier and strength multiplier in the config file...
thanks..

**Comment by frodare** [comment]
LOL, I was worried we already made it too strong.  Thanks for the suggestion b/c I would like to make it stronger too, its ToroQuest after all! :)  Or, maybe we could at a chance of a very strong toro, or one that doesn't panic and only hit once.

**Comment by kenijey** [comment]
nooooo noooo it is very weak bro, if you have diamond set and sword, it is very weak... i am using this mod in my modpack, so killing him is veerrryyy easy. please add config file that i said things at least...

**Comment by kenijey** [comment]
you may make your default toro whatever you want, but please give me a chance in config file to optimize it with my modpack. health multiplier and damage multiplier. please.

**Comment by frodare** [comment]
That would probably be easy enough ... but goodness, you are looking to make one crazy strong cow!  Also, Toros only stay agro'ed for one hit, so if you are looking for more of a challenge, we should address that too.
For the config setting, I will be making some others soon, so I will look into adding this one too.

**Comment by kenijey** [comment]
just add health multiplier man, it should be easy.. nobody will not unhappy with that.
and damage multiplier....
thanks a lot.

**Comment by frodare** [comment]
Dang dude, I said I would look into it.

**Comment by kenijey** [comment]
okay <3

**Comment by kenijey** [comment]
actually i want to make a toro family which have female toro, son toro, old toro aaand giant toro. each of them has special abilities and properties. i would really like to do it but eh............... :D

**Comment by kenijey** [comment]
thanksssssssss i love u man

**Comment by kenijey** [comment]
when will the next release  come?

**Comment by frodare** [comment]
Hopefully we will release the next version with in a couple weeks.  Here is a list of the remaining tasks: https://github.com/ToroCraft/ToroQuest/milestone/4
