### ISSUE TITLE
Village Lord Entity

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroQuest#11]
The Village Lord should be spawned in the Keep.  Maybe when killing the Lord the civilization of the village will be removed?

**Comment by zeriley** [comment]
What is the purpose of the Village Lord?  He is a quest-giver, correct?  And a potential boss?  I know we had discussed this a bit before, but we should also discuss concrete ideas for the Village Lord.  What attacks does he have, how much health, what kind of quests, etc.?

**Comment by frodare** [comment]
GUI was pulled out into another issue
