### ISSUE TITLE
Unable to buy expensive items from shopkeeper due to emerald stack limit

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroQuest#112]
![selection_012](https://cloud.githubusercontent.com/assets/795621/22448156/4b861812-e725-11e6-8bb7-3ba12372a730.png)

**Comment by Zygus42** [comment]
I know that this is not a solution, but a workaround is to use a mod called Villager Market - lets you buy stuff from all the villagers in a village directly from your inventory - tested with the example above and worked fine.

**Comment by frodare** [comment]
Nice workaround, thanks for sharing. :)
