### ISSUE TITLE
Missing ToroQuest buildings (related to other mods, I'm sure...)

### ISSUE THREAD

**Issue by nekatu** [ToroCraft/ToroQuest#113]
Not an issue with ToroQuest, per se- but would appreciate some help with missing buildings in ToroQuest.

The bulls and town markers appear, as does the ToroCraft overlay telling you which civilisation you're entering and what your standing is with them, but there's no guard towers, no lord's castle, and no NPCs.

Was working a few weeks back but I've modded quite a bit since then...

Anything from this list jump out as a potential cause?

```
ActuallyAdditions-1.11.2-r99.jar
AdChimneys-1.11.2-2.0.2.0.jar
advancedcapes-6.0.1.jar
aquamunda-0.0.6beta.jar
armorplus-1.11.2-9.5.3.4-beta.jar
Aroma1997Core-1.11.2-1.2.0.0.b81.jar
AromaBackup-1.11-2.1.0.0.b64.jar
AutoRefresh-1.11.2-1.1.0.jar
AutoRegLib-1.1-4.jar
BattleTowers-1.11.2.jar
BetterAchievements-1.11.2-0.4.1.44.jar
BetterQuesting-2.4.187.jar
BetterTitleScreen-1.11-1.3.jar
BirdsFoods-2.2.jar
Bloodmoon-MC1.11-1.5.1.jar
CanIJoinNow-1.11-1.0-1.jar
ceanimals-1.11.2-1.3.0.jar
CGUtils-1.1.jar
Chameleon-1.11-3.0.2.jar
ChestTransporter-1.11-2.6.0.jar
chiselsandbits-13.9.jar
ChunkAnimator-MC1.11-1.2.jar
ClientTweaks_1.11-2.1.2.jar
compatlayer-1.11.2-0.1.7.jar
CraftingTweaks_1.11-7.1.1.jar
cs-2.0.2.jar
CustomMainMenu-MC1.11-2.0.3.jar
cxlibrary-1.11.2-1.4.0.jar
dailies-1.11.2-6.jar
deathquotes-1.0.1-mc1.11.2-forgeBeta.jar
DebugServerInfo-1.0.0.jar
deeppockets-1.1x-1.0.0.jar
defaultgamerules-1.0.3-1.11.2.jar
dualhotbar-1.1x-1.7.2.jar
Durability Show-1.11.2-4.1.0.jar
DynamicSurroundings-1.11.2-3.2.5.0.jar
EM3R50N-EatTheEggs-1.11.2-13.20.0.2201.jar
Enchiridion-1.11.2-3.1.17.jar
environmentalcreepers-1.11.2-1.1.2.jar
FAMM-3.1.0-1.11.2.jar
FastLeafDecay-v12.jar
Fexcraft Common Library-XI.18-1.11.2.jar
forestry_1.11.2-5.3.0.31.jar
ForgeEndertech-1.11.2-2.0.2.0.jar
Forgelin-1.2.0.jar
FSMM-1.5.0-1.11.2.jar
FullscreenWindowed-1.10.2-1.5.0.jar
GiacomosFishingNet-1.11.2-1.4.8.jar
GraveStone Mod 1.7.2.jar
HelpFixer-1.11-1.4+17.jar
HowBoutThatFurniture-1.2.1.jar
Hwyla-1.8.9-B22_1.11.jar
immcraft-1.1x-1.2.6.jar
InGameInfoXML-1.11-2.8.1.91-universal.jar
invdecrap-0.9.8.3-1.11.jar
InventoryTweaks-1.62-dev-76.jar
ironchest-1.11-7.0.17.799.jar
iv-2.0.0.jar
IvToolkit-1.3.2.jar
jeibees-0.9.0.3-mc1.11.2.jar
jei_1.11.2-4.2.4.226.jar
journeymap-1.11.2-5.4.4.jar
JustEnoughResources-1.11.2-0.6.2.104.jar
lepton-1.11.2-1.3.1.jar
LevelUp!-0.13.2-1.11.jar
leveluphp-1.11-1.0.1.jar
literalascension-1.11.2-1.0.1.0.jar
llibrary-1.7.4-1.11.2.jar
LLOverlayReloaded-1.1.3-mc1.11.2.jar
Login_Shield-1.11-3-g0422a90.jar
LunatriusCore-1.11-1.1.2.39-universal.jar
Mercurius-1.11.2-1.0.2.jar
minecolonies-universal-1.11-0.6.2550.jar
MineMenu-1.11.2-1.5.0-universal.jar
Minions-1.11.2.jar
morefuelsmod-1.11.x-1.5.2.jar
MoreFurnaces-1.11-1.9.3.jar
MorePlayerModels_1.11.2(26jan17).jar
Morpheus-1.11.2-3.2.13.jar
MultiMine-1.11.2.jar
muon-0.1.jar
mysticalagriculture[1.11]-1.3.9.jar
NetherPortalFix_1.11-4.3.1.jar
NoMoreRecipeConflict-0.6(1.11).jar
Notes-1.11.2-1.1.0.jar
OptiFine_1.11.2_HD_U_B6_MOD.jar
Overlord-1.11.2-2.1.1.jar
PackingTape-1.11.0-0.6.1.jar
Ping-1.11-1.3.0.jar
placeableitems-3.0.3.1.jar
platforms-1.11.0-1.3.1.jar
progenitor-0.0.3+1.11.jar
PvPTime-1.0.12.jar
QualityOrder(0.11)-1.11.2.jar
Quark-r1.2-77.jar
RabbitsBreedLikeRabbits-Forge-1.11-7.0.0.jar
rangedpumps-0.4.jar
RealBench-1.11.2-1.3.2.jar
ReapMod 1.4.jar
ReAuth-1.11-3.4.1.jar
RecurrentComplex-1.2.8.jar
Reliquary-1.11-1.3.3.612.jar
RoguelikeDungeons-1.11.2-1.6.3.jar
roots-2-0.009.jar
rustic-0.0.3.jar
ShadowMC-1.11-3.7.4.jar
shetiphiancore-1.11.0-3.4.2.jar
simpleautoswitch-1.4.jar
simpleenhancements-v0.7.2b-mcv1.11.jar
simpleleather-1.11.2-1.0.jar
SimpleTeleporters-1.11.2-2.0.2.jar
SoundFilters-0.9_for_1.11.jar
Stackie-1.11-1.6.0.45-universal.jar
StorageDrawers-1.11.2-4.1.0.jar
sublib-1.11-1.1.3.0.jar
supercraftingframe-1.11-1.2.1.89.jar
TeamUp-1.1.3-1.11.0.jar
Tesla-1.11-1.3.0.51.jar
tesla-core-lib-1.11-0.1.0.jar
thedragonlib-1.11.2-2.2.3.jar
theoneprobe-1.1x-1.4.1.jar
thutcore-4.3.2.jar
thutessentials-1.6.8.jar
thut_bling-1.0.1.jar
thut_wearables-2.1.2.jar
topaddons-1.11.2-0.9.2.jar
torcharrows-1.11.2-2.jar
torojimaBuildHelper-0.4.2.jar
toroquest-1.11.2-2.jar
TrashSlot_1.11-7.4.1.jar
UpdateCheckerMod-1.11.jar
usefulrecipes-3.0.1.jar
VanillaMagic-1.11.2-0.21.2.1.jar
VeinMiner-1.11-0.35.3.605+dad98e1.jar
VillagerInventory-1.11-1.0.1.jar
Waddles-1.11-0.5.1.jar
Waystones_1.11-3.0.5.jar
wolfarmor-1.3.2.2.jar
WTS-1.0.1.jar
zz-backpacks 1.11.2 - 3.1.7.jar
[1.11.2]UncraftingTable-1.7.1-pre8.jar
[1.11] RPG-HUD 3.1.1.jar
```

**Comment by frodare** [comment]
That is a tough one.  There is a small chance that the structures will not generate, but if every village is missing them something is going on.  Do any of those other installed mods do anything with villages?  We tapped into the vanilla village generation so if it another mod overrides it that could stop them from being generated.  Maybe you could remove the other mods that you think might be causing the problem or that are more likely to cause it and try to narrow down when mods are incompatible.  Then if the other project is open source, I could at least skim though it and try to see what can be done.

**Comment by nekatu** [comment]
Very much what I'm thinking too- going through the list of mods to see what changes buildings.

I think the most likely one is Muon (https://minecraft.curseforge.com/projects/muon)

Issue log is here, but empty-
https://github.com/MinimumContent/muon/issues

Will post there as it sounds like it directly affects the vanilla village code and the issues definitely started not long after I first loaded that in and started a new world.

**Comment by nekatu** [comment]
Nope- wasn't that one...

Testing without BattleTowers now.

RecurrentComplex sprung to mind, but I've had ToroQuest and RecurrentComplex working together before- at least with ToroQuest taking precedence.

Know of any way of making one mod apply before/after another?
I tried the alphabetical method but didn't seem to do anything

**Comment by frodare** [comment]
I don't. Maybe start removing any of the core mods too?  I wish there was an easier way.

**Comment by nekatu** [comment]
Not either of those... :-(

No any of these either-

DynamicSurroundings
Forestry (and JeiBees)
RoguelikeDungeons

Testing if it's Roots now...

**Comment by frodare** [comment]
you might one to try dailies-1.11.2-6.jar.  That adds a village structure.  If that problem is with it that would be good b/c it is one of our mods and would be easy to fix :)

**Comment by nekatu** [comment]
I actually had that same thought, but didn't have any effect- nor did roots.

Running out of obvious candidates.

**Comment by frodare** [comment]
Make sure the problem still occurs with all of the core mods removed.  The mod works for you when it is by itself, right?

**Comment by nekatu** [comment]
Haven't tested that as yet- but next on my list after testing the removal of this mod:

https://minecraft.curseforge.com/projects/configurable-villager-to-door-ratio

**Comment by nekatu** [comment]
Bingo!

That's the one- was trying to work out what was changing the default village layouts, and that's what it was.

Shame as it was a nice layout and a great idea for a mod- but not great for the features I lost.

Thanks for your time and patience! :-)
