### ISSUE TITLE
The Loreheap

### ISSUE THREAD

**Issue by CawCawDrakon** [ToroCraft/ToroQuest#118]
A depository for the Lore I have already tought out but not written as book files. Mostly things that would be unlikely to be implement other than in bookform. 

**1. The Civilisations** 
1.1 General
- The various civilisations stem from different nomadic tribes which settled down, as well from each other.
- Which civilisations are the oldest is unclear, as well as what civilisations split from which.
  - Wolf and Terra are most likely the oldes, and Lumens most likely split from Wolf. 
  - Gustaberg and Solaris both say the other sprung from themselves
- There are nine known civilisations: The six villager civs, the nomadic tribes, the Deep Guardians, the Ancients, the Pigmen, and the Morrows
- The term "civilisations" is used pretty loosely here. The nomads refer to the other civs as "tribes", and some prefer the term "houses", a term more commonly used for factions within the civilisations
- There is also a number of small groups that don´t belong to any civilisation, such as the Dodokahedron of Shadows

1.2 Terra
- Worship Rovwelord, the embodiment of the Overworld. Consider any rock below the soil as sacred, so mining is forbidden. Instead, they use a ritual known as "Risen Flesh" to gain ore. Not much is known about it, unsurprisingly, much rumour and conjecture surrounds it.
- They specialise in brewing potions. Out of the 10 greatest alchemy researchers, 8 are Terrans. 
- When it comes to law, they are very strict. One of their most common punishments is the Test Of Soil, during which the criminal is buried to the neck for an extended period of time. 
- They consider the theory about Rovwelord having its own realm and avatar heresy, instead claiming that the Overworld itself is its body.
- Their village lords are chosen according to rules written in an obscure book. Three are chosen who then must undergo a test the winner of which becomes village lords, whereas the other two become their advisor.
- Their dead are buried within caves that are then sealed off with gravel and a "Please do not disturb the dead"-sign
- Neutral to nomads

1.3 Gustaberg
- Worship the Cloud Chicken
- Proud of having only a small number of laws, and there are multiple factions or philosophies with differing opinions as to how few:
  - Second Law: Probably the oldest of the factions. They believe only two things should be forbidden: murder and theft.
  - Third Law: The most powerful of the factions, they also forbid vandalism. 
  - Fourth Law: The second most powerful faction, this one forbids slavery as well.
  - Fifth Law: A small faction that also forbids Heresy.
  - No Law: A tiny anarchist faction.
- All crimes not covered by the the laws are dealt with on a case-to-case basis via direct vote.
- About 40% of the provinces are Third Law, 35% are Fourth Law, 15% are Second Law, 8% are Fifth Law and 2% are No Law
- There almost was a civil war between Third Law and Fourth Law, known as the Tulip Gorge Crisis. It was averted by diplomatic negotiations involving punching a Lumens ambassador.
- Gambling is an important pastime here
- Specialise in dyeing.
- The village lord is elected by popular vote and can be exiled by said vote whenever

1.4 Aquarius
- Most well known for their naval accomplishments, their culture is based on a complicated system of trust, betrayal, and atonement (sometimes at once)
- They worship the Ancient Guardian.
- They believe that Might Makes Right, so their village lord is "elected" in a kind of turnament of blood, wits, and votes. 
- Slavery is allowed here. 
- They are hostile towards the nomads. Wolf does not like that. Wolf is hostile to Aquarius.

1.5 Lumens
- Specialise in cooking and traveling the nether. 
- Worship Pyrron, and sometimes ritually destroy their own villages.
- Allow slavery. 

1.6 Solaris
- Empire of the Loving Sun, they are the only civilisation that can´t be described as a collection of city-states. They have an emperor who constantly travels between the provinces and who chooses the village lord.
- Specialise in enchanting.

1.7 Wolf
- Celebrate hospitality, just like their god-protector, Grey-Night. 
- the only civ that allows nomads to set up camp within their village walls
- In fact they will offer protection from the night even to their most hated enemies, as the dangers of the night far exceed the issues of the day.
- Their villages are mostly ruled by a Council of Elders. The village lord is its presiding member and switched out every moon. Any member of the community who has proven themselve worthy is admitted into the council.
- Their wrath for people who betrayed their trust is legendary. Tales are told of swift, invisible assassins hunting their prey for thousands of miles and of entire villages turning into wolves to crush the bones and tear the flesh of their enemies. Luckily they are much less easily angered than their god, who in their form of Blood-Night is said to be more destructive than even Pyrron, the god of destruction.
- As they believe that all dead will return as a danger of the night, they make sure there is not a scrap left of their dead. The most common method to ensure this is rumoured to be cannibalism.

1.8 The nomadic tribes
- Arguably the oldest civilisation, these are llama-herding tribes traveling the wilds to trade with civilisations and each other. 
- They don´t have an unified culture and many tribes consider themselves closer to certain civilisations than to each other
- Their religious beliefs are varied, but most worship ancestor spirits

1.9 The Ancients
- A civilisation long gone, they built the Fortresses (and other structures) and practiced magic to an extent unknown since. Are said to have either created the Overseers or at least communicated with whoever did
- Worshipped the Ender Dragon. They most likely became the Endermen, but there are accounts of Endermen existing before the Ancients vanished.

1.10 The Morrows
- A prophecied civilisation which may or may not be connected to the Unfateful Wanderer and is yet to come.
- May be a combination of all civilisations, the Ancients returned, another nomadic tribe having settled down, aliens, or something completely different

1.11 The Deep Guardians
- Probably the most alien civilisation alive today, the Deep Guardians are a species of cyclopic telekinetic fish-people living in reef-like citiy-temples deep in the ocean
- It is theorized that they originate from the realm of the Ancient Guardian, and are colonising the seas. 
- Facts are hard to come by as they are hostile to most civilisations. Even Aquarius, with whom they share a lot of cultural aspect - such as their religious beliefs, has to be very careful around them.
- The only time they have shown any interest in land affairs was during the Massacre of Pink Waves, when Aquarius tried to summon them to help defend against an attack from Wolf. The Deep Guardians slaughtered almost everyone on both sides (and some neutral people) and dragged the corpses away into the waters. Aquarius considers this a victory for themselves.
- Their language is incomprehensible and can be compared to whale song, but some scholars have begun to decipher their writing.
- There is no indication that they existed on the Overworld before the Nomadic Age, as there was found not a single Ancient text found that made reference to them - wich is odd, seeing how the Ancients had knowledge of the future. One text makes reference to what might be the Massacre of Pink Waves, but it is too vague to be clear

1.12 The (Zombie-)Pig Men 
- The Pig-Men are a species of porcine bipeds who had a sparkling civilisation during the Age of Creation
- There aren´t many accounts of their civilisation, and most of them are conflicting. There are three things known:
  - They lived in "red castles in the sky". All texts make reference these red castles, some say they were floating, a few say they were high up in the mountains
  - They made or tried to make themselves immortal using the necromantic arts. Alternatively, their lichdom might be a curse from a god who made them immortal but wasn´t given their reward. The strangest thing about these tales is that during their age, time apparently did not exist as it does today and mortality had no meaning
  - When the realms split apart, they were transported to Pyrron´s realm alongside their castles
- In the Nether, they left the castles and became a more tribal society, which exists to this day. Golden artifacts are handed down from generation to generation.
- Lumens often enslaves modern Zombie-Pigmen to have them work their fields 

**2. The Timeline**
2.1 The Age of Creation 
- The Realms are one and the Gods walk the Earth and everything happens at once
- Ends with the Realms splitting apart and time stretching out
- The most common legend about how and why this happened is this:
   - Pyrron and the Ender Dragon were dissatisfied with how hard apples were to come by
   - So they started working together and delved deep until they reached Java, who they enthralled with their magic.
   - With this enthrallment they had the power to change everything. They chose to make oak trees grow apples. 
   - Distracted by the sudden wealth of apples the usurpers stopped looking at Java for a second and Java´s bonds came undone and, wrathfully, the god of fate seperated the realms so gods could never again cooperate to overthrow them. 
   - Just out of spite, Java made sure Pyrron´s and the Enderdragon´s realms were the only ones without any apples.
- Might not have existed, the only source are arcane Ancient texts.
- Terra considers any mention of this age heresy

2.2 The Wild Age
- Only known from Ancient texts and Nomadic legends, this is the age before the Ancients and the nomads existed. 
- Some nomadic tribes might have existed back then.
- Ends with the appearence of the Ancients

2.3 The Ancient Age
- The Ancients, most likely one of the earliest nomadic tribes, settle down and built vast cities.
- They research the secrets of the void and the End, and supposedly manage to gaze into the Enderdragons vast obsidian towers, filled with the most astonishing secrets
- They vanish and everything they built on the surface crumbles to dust.

2.4 The Nomadic Age
- Nomadic tribes travel the world
- Ends with the settlement of the civilisations.
- According to the nomads, this age never ended

2.5 The Civilised Age
- The civilisations settle down and prosper.
- Each civ considers their settlement as the start of this age.
- Might be the present

2.6 The Coming Age
- The Morrows rule the lands
- Some say it starts with appearance of the Unfateful Wanderer, but given the mysterious nature of this entity this isn´t very helpful

**3. The Pantheon**
3.0 General
- In this setting, there are a number of different ways a god can be:
  - Omnipresent, incorporeal being (Java, Hapalem, The Ancestor Spirit)
  - Genus Locii, i.e. a place is their body (Rovwelord, Ivod, Tehenr)
  - Astral beings (Sol Amans, Luna, Astrals, Ivod)
  - Physical god and/or avatar, i.e. an extremely powerful being who rules over a plane of extistence (Rovwelord, Enderdragon, Ancient Guardian, Pyrron, Grey-Night/Blood-Night, Hapalem, Unfateful Wanderer, Wither)
  - Spirit (Ancestors, Unfateful Wanderer, Grey-Night/Blood-Night, Wither)
- Some are in multiple categories as there are many people describing the same thing and that sort of thing tends to get stuff scrambled up.
- Everyone believes in most of the gods, and would pray to the one most fitting the situation. 

3.1 Java, god of fate and meaning. 
- Undoubtedly the most powerful god. Gives everything meaning. Invoked by blacksmiths, and to a lesser extent, otherwise not really worshipped. Literally the programming language of the game.

3.2 Rovwelord, god of stability and strength
- According to Terra, the Genus Locii of the Overworld and the Nether - this is why they forbid any digging below the soil, as that would be the bones of a god. Nether portals are even more heretical to them - the Nether is the bowels and blood streams of a god to them. 
- Since they believe they are ants scrambling around on the skin of a giant, it makes sense that this giant is the most important god to them.
- Some nomadic tribes believe the same thing.
- Most people, however, consider Rovwelord a physical god and the Overworld the realm they rule. What - Their avatar is debated, the most common theory being that that they take the form of a either a tree, or a horse, or both.
- Rovwelord is invoked whenever someone needs patience and strength. Foundation stones often bear a prayer to them.

3.3 The Cloud Chicken, god of luck and prosperity

3.4 The Ancient Guardian, god of trust and betrayal

3.5 Pyrron, god of ambition, change, and cooking

3.6 Sol Amans, god of generosity and joy

3.7 Grey-Night, god of hospitality and safety from danger
   - Blood-Night, another form of Grey-Night and god of revenge and wrath

3.8 Hapalem, spider-god of the dangers of the night, of fear and despair

3.9 The Ender Dragon, god of knowledge and magic

3.10 The Unfateful Wanderer

3.11 Ancestor Spirits

**4. Historical people**
- Sevenj the Unbiased, a villager born in an unknown village and grown up among nomads. Tried to write to write about cultures in a completely unbiased way - the title was given to mock him but he took it gladly. Resolved the Tulip Gorge Crisis

**5. Entities**
- The wither might be an avatar of Pyrron (Lumens, Solaris), an avatar of Hapalem (Wolf, most nomads), simply a golem and weapon of mass destruction (the Ancients, Aquarius), something that is not to be spoken about (Terra), or a god of its own (Gustaberg)

**Comment by CawCawDrakon** [comment]
I will write more later, but now I don´t have the time. What do you think? What is idiotic, what is nice? Would you like to add something? It is your mod after all

**Comment by frodare** [comment]
Wow, that's a lot :)  Sorry for the late reply, I was hoping one of the other guys ( @zeriley @mrprim ) would hop in on this one ... this is outside my skillz ;)  I do like where this is going though!

**Comment by frodare** [comment]
One thing I would like to work in (one of @zeriley 's ideas) is that every civilization would have an enemy.  I like this idea because it might provide motivation for a player to have negative rep.  They could be set as:

Aquarius vs Lumens
Terra vs Gustaberg
Wolf vs Solaris

**Comment by CawCawDrakon** [comment]
What about each having one enemy and an ally, like
Wolf (allied with Gustaberg and Terra) vs Aquarius (allied with Lumens)
Solaris (allied with Aquarius and Terra) vs Gustaberg (allied with Lumens and Wolf)
Terra (allied with Wolf and Solaris) vs Lumens (allied with Gustaberg and Aquarius)
(This makes more sense given the lore.)

Also, would it be possible to include a simple political system you can influence with diplomatic quests?
Like, if two civs are at war and you aren´t enemy to either of them, you can get quests to negotiate peace or to ask an ally for help, changing the relationship between the civs.
If two civs are neutral to each other (and you are at least an ally to either of them) you could get a quest to attack the other, making them hostile to each other. Or a diplomatic quest to bring the other a gift, making them allies.

**Comment by zeriley** [comment]
I'm back in town now, so I'll be catching up on stuff and will take a look at this in the next few days and provide feedback.  Thanks, @frodare for taking care of all the ToroCraft issues while I was away.  Hopefully I can take some of your load soon (mmmm...).

**Comment by CawCawDrakon** [comment]
Updated Pantheon

**Comment by CawCawDrakon** [comment]
Updated Eras
