### ISSUE TITLE
Create Shopkeep Entity

### ISSUE THREAD

**Issue by mrprim** [ToroCraft/ToroQuest#12]
Need a shopkeep entity that will spawn in shops.

Shopkeep needs:
- GUI for trading/selling things
- AI to keep him in the front part of the shop if no zombies around.
- POSSIBLE: Price fluctuation based on civ rep level

**Comment by zeriley** [comment]
We need to discuss what the shopkeep can sell and for how much.  I would think we don't want to completely nullify villager trading, so maybe we should consider no/very little overlap with what villagers trade for.
