### ISSUE TITLE
FPS is decreasing when looking to the village

### ISSUE THREAD

**Issue by kenijey** [ToroCraft/ToroQuest#120]
my normal fps is 80-100, in forest jungle 50-60 but when i come to the village and look to the buildings or directly the village, fps is being 20-30. is it my problem? please help :(

**Comment by frodare** [comment]
Are you sure this is a ToroQuest issue?

**Comment by kenijey** [comment]
yeah it is..

**Comment by SDUBZ** [comment]
i can confirm this also happens to mostly due to causing world cascading lag 
ToroQuest loaded a new chunk (203, 59  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by frodare** [comment]
@SDUBZ that looks like it was caused while generating a new chunk.  If so it was probably one of the larger dungeons being generated which could definitely cause a lag spike.  It shouldn't cause a drop in FPS though when looking in a certain direction.

**Comment by SDUBZ** [comment]
well @frodare when toroquest is disabled when in a village no fps drops happen so maybe its all the ai spawning and updating at once causing it when a village generates

**Comment by frodare** [comment]
If you are getting FPS drops not related to world gen then I agree, it is most likely in the AI.  Unfortunately I haven't found any obvious fixes yet or experienced it myself.  I will keep this issue open to remind me to look around more in the entity AI code before releasing a new version.

**Comment by frodare** [comment]
Sorry guys, I haven't been able to find what is causing your FPS drop.  I even tried spawning a bunch of TQ entities to see if I could reproduce this.  If you are able to find a way to reproduce this bug with TQ as the only installed mod, please post it here and I will try it out.

![2017-06-22_20 00 17](https://user-images.githubusercontent.com/795621/27460987-8e4982da-5785-11e7-9a04-67945726ae5a.png)
