### ISSUE TITLE
[*] [[REQUEST]] Better Badge Placement

### ISSUE THREAD

**Issue by kreezxil** [ToroCraft/ToroQuest#125]
When doing custom badge placement you don't actually provide a mechanism to get it flushed to the right side of the screen. I propose adding ~ to the coordinate system to allow for inversion, that way I can set my x to ~20 to indicate 20 pixels from the right side of the screen going towards the left side.

If you have a mechanism in place for that, please elaborate here, in the config and on the overview. Thank you. :)

**Comment by frodare** [comment]
I think I get you, actually, I just implemented that in one of our other mods.  I will look into doing the same in ToroQuest

**Comment by frodare** [comment]
The badge placement improvements have been added version 3.3, please give it a shot and let me know if it is what you had in mind.
