### ISSUE TITLE
Reputation Control

### ISSUE THREAD

**Issue by HypnoPants** [ToroCraft/ToroQuest#126]
Is there a way to edit the config to allow for killing animals or taking crops without losing reputation?

**Comment by frodare** [comment]
Not currently, that wouldn't be difficult.  I will add it to the next release.

**Comment by HypnoPants** [comment]
Thanks, I'd really appreciate it. I'm playing with the minecolonies mod, and I started expanding a toroquest town, so that not only was it more amazing and productive but the added bonus of the sentries was amazing... it all fit perfectly, and the villagers of course can still use the minecolonies buildings too. It made for the best of both worlds! ... except when I realised I was losing rep for killing animals in a pen I placed down there, and for taking crops even though I was replanting them. =P

**Comment by frodare** [comment]
In the mean time, you actually gain rep by breeding animals b/c it gives you 2 points vs removing 1 point to kill them.  An if you build a water harvester for your crops (or just use a water bucket) you can gain rep from crops too.  I still plan on adding the an option for it though, thx for the suggestion :)

**Comment by HypnoPants** [comment]
You're Welcome :)

**Comment by frodare** [comment]
The new config options have been added version 3.3, please give it a shot and let me know if it is what you had in mind.

**Comment by HypnoPants** [comment]
Just tested it out, it was perfect. :) Thanks!

My wife and friends were all a little distraught... I had convinced them to build in a toroquest town, which they liked at first... they didn't realise how much rep they were losing until it was too late :P 

so thank you :)
