### ISSUE TITLE
Just Another Crash...

### ISSUE THREAD

**Issue by kenijey** [ToroCraft/ToroQuest#127]
please help... i just installed forge 2253... and latest TQ... game won't start
[crash-2017-03-06_11.30.36-client.txt](https://github.com/ToroCraft/ToroQuest/files/820516/crash-2017-03-06_11.30.36-client.txt)
please help :c

**Comment by kenijey** [comment]
please help :c

**Comment by frodare** [comment]
I was actually just looking into to it.  It looks like a mod compatibility issue.  The bad news: you need to figure out which mod is not compatible. The good news: I will be happy to attempt to fix TQ to make it compatible.  Please test TQ alone to verify it works, if it does you will need to test TQ alone with just one mod at a time to find the mod causing the problem. Start with mods you think to be more likely to be causing the problem.  Once you find it I will work on a patch.  However if TQ crashes when it is the only mod, please send me the crash report.

**Comment by kenijey** [comment]
i will cry now... there are 158 mods :'( can anything help me find which mod causes?

**Comment by frodare** [comment]
Maybe something that deals with adding or changing stats for when entities are killed: stat.entityKill.  Start with the core mods, chances are it would be one of those.

**Comment by kenijey** [comment]
oh wait, this happened after my modpacks last version. i added 5 mods in that update, i will try deleting them. give me 5 mins.

**Comment by kenijey** [comment]
okay, i found the mod. it is elemental dimensions that causes crash with toroquest. waiting for your help :)

**Comment by frodare** [comment]
Nice! I will look into it when I get home.

**Comment by kenijey** [comment]
okay

**Comment by frodare** [comment]
Looks like a name conflict with one of these dudes

![selection_034](https://cloud.githubusercontent.com/assets/795621/23636467/837a5e9c-02a3-11e7-9363-810afeb969c8.png)

**Comment by frodare** [comment]
I am kind of stuck on this one.  I can change the name of the Guard and make it work, but if I do, all of the Guards currently in the game will vanish. That would be a problem for all other players using the mod.  I was under the assumption that the entity names were name spaced under the mod ID, I guess that is not case :(

**Comment by kenijey** [comment]
We believe you can fix it :) and we are using the one probe

**Comment by frodare** [comment]
That's good to hear! I am going to close the issue since I have no way to fix this problem without breaking current games.  Maybe down the road I will step the version, rename all the entities to something more specific and not worry about compatibility.

**Comment by kenijey** [comment]
so? how much should we wait for the hotfix version fixes this crash?

**Comment by frodare** [comment]
Oh I miss read your comment above, I thought you found a way to fix it this.  I have one more idea I could try.  Maybe if I made a config option that would let you change "Use Compatible Names". Then when you set that I would register the entities with more specific names like `toroquest_guard` instead of just `guard`.  All of the current entities would vanish from your game though.  What do you think?

**Comment by kenijey** [comment]
you should add a config to rename the guards. for example, i may want to rename them with "asker" :) or, "sentinel" only. you can find many names for guards, such as the nations in the world. every nation has its own guard name.  ust add a config about it. it will help :) thanks a lot.

**Comment by kenijey** [comment]
and please tell how much should we wait :D

**Comment by frodare** [comment]
No promises but I will try to get the new config option working tonight and a new release withing a few days.   If I make a setting it will change all of the generic names I am using not just the guard, so other entities will vanish too.  For starting new games that will not be a problem though.  And this is just the code name it can be translated in the lang files.

**Comment by kenijey** [comment]
okay. get luck with! thanks

**Comment by frodare** [comment]
OK, I have a potential fix in version 3.3, please give it a try and let me know how it goes.

**Comment by kenijey** [comment]
hello.
i tried installing latest version. it helped the crash. it works fine. Thanks a lot! =)
