### ISSUE TITLE
No Guards, No King, No NPC

### ISSUE THREAD

**Issue by kenijey** [ToroCraft/ToroQuest#131]
why is it like this ::(((
![2017-03-13_20 06 11](https://cloud.githubusercontent.com/assets/24831406/23866039/3f373624-0820-11e7-91fa-4f949959ce73.png)
what information should i give?
using game 1.11.2, forge 2255, latest TQ
[fml-client-latest.log.txt](https://github.com/ToroCraft/ToroQuest/files/839018/fml-client-latest.log.txt)
and here is latest fml log

**Comment by kenijey** [comment]
please help me :(

**Comment by frodare** [comment]
are you talking about the wood steps?

**Comment by kenijey** [comment]
no mate :D all about the title, no any guards, no king, no npcs.

**Comment by frodare** [comment]
LOL right.  Did you set the new config option to use non-conflicting entity names?  That will clear all TQ entities that previously existed as stated, but it should default to false.  Please test in creative mode to see if they show up for new villages and if you can spawn them using eggs.

**Comment by kenijey** [comment]
my TQ config is like this
![tq config](https://cloud.githubusercontent.com/assets/24831406/23866775/824f7a50-0822-11e7-8113-89c46332cacb.PNG)

**Comment by kenijey** [comment]
but as you remember, you said i should set that option true to make it compatible with elemental dimensions. then i must delete elemental dimensions mod??

**Comment by frodare** [comment]
If you are starting a new world, it should all work.  If you have an existing world and turn that option on it will remove all of the existing TQ entities, however all new villages found should work normally.  If you want to keep the old world and set this option to true, you will need to use some spawn eggs to add the entities back assuming someone is OP.  I wish I had a better solution, but that is all I could think of.

**Comment by kenijey** [comment]
are u sure? as i remember, i created a new world THEN it crashed with elemental dimensions mod. ok i will try it now give me 5 mins.

**Comment by kenijey** [comment]
it worked. thanks!

**Comment by frodare** [comment]
shew, n/p :)
