### ISSUE TITLE
[bug] crash when handing in item for reputation

### ISSUE THREAD

**Issue by Zygus42** [ToroCraft/ToroQuest#135]
Crash when handing in enchanted gold sword that was going to give 1 reputation:
[crash-2017-03-23_14.47.12-client.txt](https://github.com/ToroCraft/ToroQuest/files/863842/crash-2017-03-23_14.47.12-client.txt)

**Comment by frodare** [comment]
I have verified this bug and will make a patch for it soon. This looks like a bug cashed from backporting from the 1.11.2 version.

**Comment by frodare** [comment]
ToroQuest 1.10.2-3.2.2 should fix this issue, thanks.
