### ISSUE TITLE
Crash w/ Repose Mod

### ISSUE THREAD

**Issue by WenXin20** [ToroCraft/ToroQuest#136]
I got this crash after a block fell. The repose mod makes it so that other blocks can fall from gravity.
Forge 2254
[Repose](https://minecraft.curseforge.com/projects/repose) v1.5
ToroQuest v3.2.1
[Crash Report](http://pastebin.com/1La7vHsw)

**Comment by frodare** [comment]
https://github.com/ToroCraft/ToroQuest/blob/1.10.2/java/net/torocraft/toroquest/civilization/quests/QuestMine.java#L59

This looks like yet another bug caused from the backport, should be easy to fix.

**Comment by WenXin20** [comment]
Thanks

**Comment by frodare** [comment]
ToroQuest 1.10.2-3.2.2 should fix this issue, thanks.
