### ISSUE TITLE
Toroquest coming up in crash report.

### ISSUE THREAD

**Issue by 1800Doctorb** [ToroCraft/ToroQuest#137]
I haven't been able to replicate this bug completely. I seems to crash anywhere in my world but more occasionally around the castles and villages.

Here is the report.

[crash-2017-03-23_17.51.29-server.txt](https://github.com/ToroCraft/ToroQuest/files/866599/crash-2017-03-23_17.51.29-server.txt)

**Comment by frodare** [comment]
Crash w/ Repose Mod #136
