### ISSUE TITLE
GUI Opaque Glitch

### ISSUE THREAD

**Issue by kenijey** [ToroCraft/ToroQuest#139]
hello... i have an amazing problem. it is about the GUI. i am using my own texture pack which made by me; and my hotbar normally looks like this:
![normal](https://cloud.githubusercontent.com/assets/24831406/24752807/2a1f29fc-1ad8-11e7-9fa9-74335782313d.PNG)
But, if i get closer to a village(toro village) the village info GUI comes on the screen, and hotbar being like this(opaque killed):
![torobug](https://cloud.githubusercontent.com/assets/24831406/24752834/4ae94bae-1ad8-11e7-9e6b-b772a1aea90c.PNG)
please help it. i spent many hours to make that hotbar :( thanks...
minecraft 1.11.2 forge 2264

**Comment by kenijey** [comment]
it has been solved when i set gui position to TOP_RIGHT

**Comment by frodare** [comment]
Sorry we never got back to you on this one! Glad you figured out a way to fix it though.

**Comment by kenijey** [comment]
i opened new issue instead of reopening this..
