### ISSUE TITLE
Create special items/armor for each civilization

### ISSUE THREAD

**Issue by Wing01** [ToroCraft/ToroQuest#14]

**Comment by zeriley** [comment]
Ideas for items each civilization can sell.  To discuss.

Fire:
   - Armor with Fire Protection
   - Swords with Fire Aspect
   - Bows with Flame
   - Buckets of lava
   - All fire-related enchanted books
Earth:
   - Pickaxes with max Efficiency
   - Pickaxes with Fortune
   - Pickaxes with Silk Touch
   - All digging-related enchanted books
Wind:
   - Swords with Knockback
   - Bows with Punch
   - Boots with Feather Falling
Water:
   - Helmets with Respiration and Aqua Affinity
   - Boots with Depth Strider
   - Stuff from Ocean Temples like lamps?
   - All water-related enchanted books
Sun:
   - Armor with Blast Protection
   - Swords with Smite and Sharpness
Moon:
   - Cursed weapons/armor
       - we could create a bunch of weapons/armor/enchantments that have side effects, like extra sharpness at the cost of durability
   - Alternatively, all mob-related enchantments like Smite and Bane of Arthropods

**Comment by zeriley** [comment]
For the cursed weapons/armor, I think we should not display what the effects are.  It always just shows Cursed Sword or whatever, then you have to use it to figure out the benefits and drawbacks.

**Comment by frodare** [comment]
Special Custom Items For Civilizations:

**Wind**: Mage Staff?
**Earth**: Toro Armor
**Fire**: Glass Sword
**Moon**: ?
**Sun**: Samurai Armor
**Water**: ?
