### ISSUE TITLE
How To Disable the GUI (rep)

### ISSUE THREAD

**Issue by kenijey** [ToroCraft/ToroQuest#140]
i tried     S:"Rep Badge Position"=OFF
but didn't work. what should i do to disable it? thanks.

**Comment by frodare** [comment]
That wasn't build in.  I just uploaded a new version that allows you to turn the HUD off.

**Comment by kenijey** [comment]
so i can disable it by setting it "OFF" right? thanks.

**Comment by kenijey** [comment]
thanks!
