### ISSUE TITLE
Config option for sentry damage

### ISSUE THREAD

**Issue by frenzye** [ToroCraft/ToroQuest#143]
Right now with an iron sword they can 1hit a player in fully upgraded draconic armor, so them having much better gear or a config option to lower their damage would be nice

**Comment by frodare** [comment]
I can add a config option for that.  For reference it is currently set to 3 and an enderman does 7.  It would be cool to make them spawn with different sword types too, based on what their attack damage is set to.

**Comment by frenzye** [comment]
a mod in my pack somehow is giving sentries 4096 damage, giving them complete control all throughout the lands

**Comment by frodare** [comment]
Wow, that would be intimidating, any idea which mod?

**Comment by frenzye** [comment]
Scaling health has a scaling damage multiplier option, disabling that fixed the sentries damage

**Comment by frodare** [comment]
Awesome, thanks for letting me know.  I will close this issue now that you figured out how to fix it.
