### ISSUE TITLE
Config Health and Damage Multiplier for the bosses

### ISSUE THREAD

**Issue by kenijey** [ToroCraft/ToroQuest#144]
please help this, because i installed toroquest in my modpack and players kills bosses with 3 hits. thanks..
using forge 2285, mc 1.11.2

**Comment by frodare** [comment]
This makes sense to me. We will add this feature when development for this mod picks up again.

**Comment by kenijey** [comment]
okay ^^

**Comment by frodare** [comment]
ToroQuest 1.11.2-3.5 is now deployed with a fix for this issue.

**Comment by kenijey** [comment]
thanks a lot!
