### ISSUE TITLE
Crash With Modern Warfare Mod

### ISSUE THREAD

**Issue by kenijey** [ToroCraft/ToroQuest#145]
[crassh.txt](https://github.com/ToroCraft/ToroQuest/files/981044/crassh.txt)
thanks..
and i don't say it's toroquest's fault.
forge 2294.

**Comment by frodare** [comment]
https://github.com/ToroCraft/ToroQuest/blob/master/java/net/torocraft/toroquest/civilization/quests/QuestKillMobs.java#L71

Looks like this can be fixed fairly easily with some additional NULL checking.  I will try to get a new release out tonight with a fix.

Thanks for reporting the issue.

**Comment by kenijey** [comment]
thanks a lot

**Comment by frodare** [comment]
This should be fix in the next release which should land in the new few days.

**Comment by frodare** [comment]
ToroQuest 1.11.2-3.5 is now on curse with a fix for this issue.
