### ISSUE TITLE
Crash with Aether Legacy [1.11.2]

### ISSUE THREAD

**Issue by Rafilondon** [ToroCraft/ToroQuest#146]
Happens when starting the game. Latest Forge Version.

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  FarseekCoreMod (Farseek-1.11-2.1.jar)
  ForgelinPlugin (Forgelin-1.2.0.jar)
  BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.5.jar)
  LittlePatchingLoader (LittleTiles v1.4.6 mc1.11.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  CreativePatchingLoader (CreativeCore v1.7.0 mc1.11.2.jar)
  IvToolkit (IvToolkit-1.3.2.1.jar)
  DummyPlugin (ForgeEndertech-1.11.2-2.0.8.0-build.0025.jar)
  DLFMLCorePlugin (DynamicLights-1.11.2.jar)
  LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  LoadingPlugin (Quark-r1.2-91.jar)
  PotionCoreFMLLoadingPlugin (PotionCore-1.5_for_1.11.2.jar)
  SHLoadingPlugin (ScalingHealth-1.11.x-1.0.4-46.jar)
  TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.3.3.1.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 5/6/17 5:32 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ToroQuest (toroquest)
Caused by: java.lang.RuntimeException: Duplicate stat id: "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.sentry.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" and "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.sentry.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" at id stat.killEntity.sentry
	at net.minecraft.stats.StatBase.func_75971_g(SourceFile:42)
	at net.minecraft.stats.StatList.func_151182_a(StatList.java:306)
	at net.minecraft.entity.EntityList$EntityEggInfo.<init>(EntityList.java:412)
	at net.minecraftforge.fml.common.registry.EntityRegistry.registerEgg(EntityRegistry.java:220)
	at net.minecraftforge.fml.common.registry.EntityRegistry.registerModEntity(EntityRegistry.java:171)
	at net.torocraft.toroquest.entities.EntitySentry.init(EntitySentry.java:45)
	at net.torocraft.toroquest.entities.ToroQuestEntities.init(ToroQuestEntities.java:14)
	at net.torocraft.toroquest.CommonProxy.init(CommonProxy.java:68)
	at net.torocraft.toroquest.ClientProxy.init(ClientProxy.java:23)
	at net.torocraft.toroquest.ToroQuest.init(ToroQuest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:828)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:356)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2770550368 bytes (2642 MB) / 4075814912 bytes (3887 MB) up to 4075814912 bytes (3887 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096M -Xms3048M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 Optifine OptiFine_1.11.2_HD_U_B7 121 mods loaded, 121 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282.jar) 
	UCHI	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282.jar) 
	UCHI	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHI	ivtoolkit{1.3.2.1} [IvToolkit] (minecraft.jar) 
	UCHI	littletilescore{1.0.0} [LittleTilesCore] (minecraft.jar) 
	UCHI	potioncore_coremod{1.5_for_1.11.2} [Potion Core Coremod] (minecraft.jar) 
	UCHI	dmonsters{1.15} [Deadly Monsters] (1.11.2_deadly_monsters_1.15.jar) 
	UCHI	forgeendertech{1.11.2-2.0.8.0} [Forge Endertech] (ForgeEndertech-1.11.2-2.0.8.0-build.0025.jar) 
	UCHI	adchimneys{1.11.2-2.0.9.1} [Advanced Chimneys] (AdChimneys-1.11.2-2.0.9.1-build.0040.jar) 
	UCHI	advancedcapes{6.0 EXPERIMENTAL} [Advanced Capes] (advancedcapes-7.0.jar) 
	UCHI	aether_legacy{v1.4.1} [Aether Legacy] (aether_legacy-1.11.2-1.0.jar) 
	UCHI	animania{1.0.4.7} [Animania] (animania-1.11.2-1.0.4.7.jar) 
	UCHI	applecore{2.1.2} [AppleCore] (AppleCore-mc1.11.2-2.1.2.jar) 
	UCHI	aquaculture{1.5.0} [Aquaculture] (Aquaculture-1.11.2-1.5.0.33.jar) 
	UCHI	quark{r1.2-91} [Quark] (Quark-r1.2-91.jar) 
	UCHI	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHI	barkifier{1.0} [Barkifier] (Barkifier MC1.11.2 v1.0.jar) 
	UCHI	battletowers{1.5.5} [Battle Towers] (BattleTowers-1.11.jar) 
	UCHI	baubles{1.4.4} [Baubles] (Baubles-1.11-1.4.4.jar) 
	UCHI	betterwithmods{1.1.7} [Better With Mods] (Better With Mods-1.1.7-1.11.2.jar) 
	UCHI	betterachievements{0.4.1.44} [Better Achievements] (Better-Achievements-Mod-1.11.2.jar) 
	UCHI	betterfoliage{2.1.5} [Better Foliage] (BetterFoliage-MC1.11.2-2.1.5.jar) 
	UCHI	biomesoplenty{6.1.0.2193} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.1.0.2193-universal.jar) 
	UCHI	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.11-1.5.1.jar) 
	UCHI	chameleoncreepers{1.4.1} [Chameleon Creepers] (chameleoncreepers-1.4.2-1.11.2.jar) 
	UCHI	chesttransporter{2.6.0} [Chest Transporter] (ChestTransporter-1.11-2.6.0.jar) 
	UCHI	cosmeticarmorreworked{1.11.2-v1a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.11.2-v1a.jar) 
	UCHI	crackedzombiemod{3.6.2} [CrackedZombie Mod] (crackedzombiemod-1.11.2-3.6.2-82.jar) 
	UCHI	creativecore{1.5.0} [CreativeCore] (CreativeCore v1.7.0 mc1.11.2.jar) 
	UCHI	customizeddungeonloot{1.0.1} [§eCustomized Dungeon Loot] (Customized Dungeon Loot 1.11.2 (v.1.0.1).jar) 
	UCHI	dailies{1.11.2-6} [Bailey's Dailies] (dailies-1.11.2-6.jar) 
	UCHI	dirt2path{1.4.0} [Dirt2Path] (dirt2path-1.4.0.jar) 
	UCHI	dynamiclights{1.4.6} [Dynamic Lights] (DynamicLights-1.11.2.jar) 
	UCHI	dynamiclights_onfire{1.0.7} [Dynamic Lights on burning] (DynamicLights-1.11.2.jar) 
	UCHI	dynamiclights_creepers{1.0.6} [Dynamic Lights on Creepers] (DynamicLights-1.11.2.jar) 
	UCHI	dynamiclights_dropitems{1.1.0} [Dynamic Lights on ItemEntities] (DynamicLights-1.11.2.jar) 
	UCHI	dynamiclights_entityclasses{1.0.1} [Dynamic Lights on specified Entities] (DynamicLights-1.11.2.jar) 
	UCHI	dynamiclights_mobequipment{1.1.0} [Dynamic Lights on Mob Equipment] (DynamicLights-1.11.2.jar) 
	UCHI	dynamiclights_flamearrows{1.0.1} [Dynamic Lights on Flame enchanted Arrows] (DynamicLights-1.11.2.jar) 
	UCHI	dynamiclights_floodlights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.11.2.jar) 
	UCHI	dynamiclights_otherplayers{1.0.9} [Dynamic Lights Other Player Light] (DynamicLights-1.11.2.jar) 
	UCHI	dynamiclights_theplayer{1.1.3} [Dynamic Lights Player Light] (DynamicLights-1.11.2.jar) 
	UCHI	dsurround{3.3.3.1} [Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.3.3.1.jar) 
	UCHI	embers{0.210} [Embers] (embers-0.210.jar) 
	UCHI	epicsiegemod{12.0.153} [Epic Siege Mod] (EpicSiegeMod-12.0.153.jar) 
	UCHI	fairylights{2.1.0} [Fairy Lights] (fairylights-2.1.0-1.11.2.jar) 
	UCHI	farseek{2.1} [Farseek] (Farseek-1.11-2.1.jar) 
	UCHI	floricraft{2.0.2} [Floricraft] (Floricraft-1.11.2-2.0.2.jar) 
	UCHI	foodexpansion{1.3} [Food Expansion] (FoodExpansion1.3.1-1.11.2.jar) 
	UCHI	forestry{5.3.3.95} [Forestry] (forestry_1.11.2-5.3.3.95.jar) 
	UCHI	examplemod{1.0} [examplemod] (forgecreeperheal-1.11.2-1.3.0.jar) 
	UCHI	forgecreeperheal{1.3.0} [[Unofficial] Forge Creeper Heal] (forgecreeperheal-1.11.2-1.3.0.jar) 
	UCHI	hcmw{1.0} [Homecraft Mineware] (hcmw-1.11.2-0.3.0.1-universal.jar) 
	UCHI	hungerpersistence{1.0.1} [Hunger Persistence] (HungerPersistence-mc1.11.2-1.0.1.jar) 
	UCHI	infernalmobs{1.7.2} [Infernal Mobs] (InfernalMobs-1.11.2.jar) 
	UCHI	irishluck{0.3.5C} [Irish Luck] (IrishLuck-0.3.5C-MC[1.11].jar) 
	UCHI	iymts_mod{1.11.2-0.0.2} [iYAMATO's Mod] (iYAMATOs_mod-1.11.2-0.0.8.jar) 
	UCHI	jei{4.2.9.245} [Just Enough Items] (jei_1.11.2-4.2.9.245 .jar) 
	UCHI	kalstuff{0.8.1} [KalStuff] (KalStuff-1.11.2-0.8.1.jar) 
	UCHI	levelup{${version}} [Level Up!] (LevelUp!-0.14.4-1.11.2.jar) 
	UCHI	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.11.jar) 
	UCHI	literalascension{1.11-1.0.0.1} [Literal Ascension] (literalascension-1.11-1.0.0.1.jar) 
	UCHI	littletiles{1.3.0} [LittleTiles] (LittleTiles v1.4.6 mc1.11.2.jar) 
	UCHI	malisiscore{1.11.2-5.1.1} [MalisisCore] (malisiscore-1.11.2-5.1.1.jar) 
	UCHI	malisisdoors{1.11.2-6.1.0} [MalisisDoors] (malisisdoors-1.11.2-6.1.0.jar) 
	UCHI	minecolonies{1.11.2-0.7.811} [MineColonies] (minecolonies-universal-1.11.2-0.7.811.jar) 
	UCHI	missing_pieces{4.1.1} [Missing Pieces] (missing_pieces-1.11-4.1.3.jar) 
	UCHI	moreplayermodels{1.11.0} [MorePlayerModels] (MorePlayerModels_1.11.0(03dec16).jar) 
	UCHI	shetiphiancore{3.4.4} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.4.jar) 
	UCHI	multibeds{1.3.2} [Multi-Beds] (multibeds-1.11.0-1.3.2.jar) 
	UCHI	multistorage{1.3.6} [Multi-Storage] (multistorage-1.11.0-1.3.6.jar) 
	UCHI	mxtune{0.4.0-dev.22} [mxTune] (mxtune-1.11.2-0.4.0-dev.22.jar) 
	UCHI	neat{1.4-13} [Neat] (Neat 1.4-13.jar) 
	UCHI	recipehandler{0.8} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.8(1.11).jar) 
	UCHI	opframe{0.1} [OnlinePictureFrame] (OnlinePicFrame v1.3.4 mc1.11.2.zip) 
	UCHI	overlord{2.3.7} [Overlord] (Overlord-1.11.2-2.3.7.jar) 
	UCHI	petbat{1.4.7} [Pet Bat] (PetBat-1.11.2.jar) 
	UCHI	stellarapi{0.6.4.1.2} [Stellar API] (Stellar API-0.6.4.1.2.jar) 
	UCHI	photoptics{0.6.1.1.1} [Photoptics] (Photoptics-0.6.1.1.1.jar) 
	UCHI	platforms{1.3.4} [Platforms] (platforms-1.11.0-1.3.4.jar) 
	UCHI	potioncore{1.5_for_1.11.2} [Potion Core] (PotionCore-1.5_for_1.11.2.jar) 
	UCHI	qualitytools{1.0.1_for_1.11.2} [Quality Tools] (QualityTools-1.0.1_for_1.11.2.jar) 
	UCHI	realdrops{1.1.10} [Realistic Item Drops] (RealisticItemDrops-1.1.10.jar) 
	UCHI	reccomplex{1.3} [Recurrent Complex] (RecurrentComplex-1.3.jar) 
	UCHI	xreliquary{1.11.2-1.3.3.653} [Reliquary] (Reliquary-1.11.2-1.3.3.653.jar) 
	UCHI	reptilemod{3.6.2} [Reptile Mod] (reptilemod-1.11.2-3.6.2-67.jar) 
	UCHI	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHI	roots{0.010} [Roots 2] (roots-2-0.011.jar) 
	UCHI	ropebridge{2.0.5} [Rope Bridge] (ropebridge-1.11.2-2.0.5.jar) 
	UCHI	roughmobs{1.0} [Rough Mobs] (roughMobs1.0.9-1.11.2.jar) 
	UCHI	silentlib{2.0.3} [Silent Lib] (SilentLib-1.11.x-2.0.3-43.jar) 
	UCHI	scalinghealth{1.0.4} [Scaling Health] (ScalingHealth-1.11.x-1.0.4-46.jar) 
	UCHI	sophisticatedwolves{3.6.5} [Sophisticated Wolves] (SophisticatedWolves-3.6.5.jar) 
	UCHI	spartanshields{1.3} [Spartan Shields] (SpartanShields-1.11.2-1.3.jar) 
	UCHI	spiceoflife{1.3.7} [The Spice of Life] (SpiceOfLife-mc1.11.2-1.3.7.jar) 
	UCHI	spikemod{1.11.2-1.2.1} [Spike Mod] (spikemod-1.11.2-1.2.1.jar) 
	UCHI	stellarsky{0.6.5.1.4} [Stellar Sky] (Stellar Sky-0.6.5.1.4.jar) 
	UCHI	stg{1.11.2-1.1.1} [SwingThroughGrass] (stg-1.11.2-1.1.1.jar) 
	UCHI	storageboats{2.0} [Storage Boats Mod] (StorageBoats-2.2.jar) 
	UCHI	streams{0.3} [Streams] (Streams-1.11-0.3.jar) 
	UCHI	substratum{1.9.2.0} [Substratum] (Substratum-1.11.2-1.9.2.0.jar) 
	UCHI	survivaltweaks{4.0.1} [Survival Tweaks] (SurvivalTweaks-4.0.1-1.11.2.jar) 
	UCHI	tammodized{0.8.4} [TamModized] (TamModized-1.11.2-0.8.4.jar) 
	UCHI	thutcore{4.4.0} [ThutCore] (thutcore-4.4.0.jar) 
	UCHI	thuttech{5.0.0} [Thut's Tech] (thuttech-5.0.0.jar) 
	UCHI	toolbelt{1.6.1} [Tool Belt] (ToolBelt-1.11.2-1.6.1.jar) 
	UCHI	torohealthmod{1.11.2-9} [ToroHealth Damage Indicators] (torohealth-1.11.2-9.jar) 
	UCHE	toroquest{1.11.2-3.2} [ToroQuest] (toroquest-1.11.2-3.2.jar) 
	UCHI	totemic{1.11.2-0.8.3} [Totemic] (Totemic-1.11.2-0.8.3.jar) 
	UCHI	toughasnails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.11-2.0.5.jar) 
	UCHI	treechopper{1.1.1a} [Tree Chopper] (TreeChopper-1.11-1.1.1a.jar) 
	UCHI	vc{4.30.29} [ViesCraft] (ViesCraft-1.11.2-4.30.29.jar) 
	UCHI	voidcraft{0.18.5} [VoidCraft] (VoidCraft-1.11.2-0.18.5.jar) 
	UCHI	waddles{0.5.1} [Waddles] (Waddles-1.11-0.5.1.jar) 
	UCHI	waystones{3.0.13} [Waystones] (Waystones_1.11.2-3.0.13.jar) 
	UCHI	weaponcaseloot{5.0.3-beta} [WeaponCaseLoot] (weaponcaseloot-1.11.2-5.0.3-beta.jar) 
	UCHI	wearablebackpacks{2.1.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.1.0.jar) 
	UCHI	thejungle{1.0.194} [Welcome to the Jungle] (Welcome to the Jungle-1.04.1112.jar) 
	UCHI	zeiyocraft{0.8.1} [ZeiyoCraft] (zeiyocraft-0.8.1.jar) 
	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
FarseekCoreMod (Farseek-1.11-2.1.jar)
  farseek.core.FarseekClassTransformer
ForgelinPlugin (Forgelin-1.2.0.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.5.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
LittlePatchingLoader (LittleTiles v1.4.6 mc1.11.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  shetiphian.core.asm.ClassTransformer
CreativePatchingLoader (CreativeCore v1.7.0 mc1.11.2.jar)
  
IvToolkit (IvToolkit-1.3.2.1.jar)
  
DummyPlugin (ForgeEndertech-1.11.2-2.0.8.0-build.0025.jar)
  
DLFMLCorePlugin (DynamicLights-1.11.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
LoadingPlugin (Quark-r1.2-91.jar)
  vazkii.quark.base.asm.ClassTransformer
PotionCoreFMLLoadingPlugin (PotionCore-1.5_for_1.11.2.jar)
  com.tmtravlr.potioncore.asm.ArmorHandlerTransformer
SHLoadingPlugin (ScalingHealth-1.11.x-1.0.4-46.jar)
  net.silentchaos512.scalinghealth.asm.SHClassTransformer
TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.3.3.1.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 381.89' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	forestry : Plugins have been disabled in the config: Food, Greenhouse, Arboriculture, Energy, Farming, Mail, Factory, Storage
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 381.89
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8`

**Comment by frodare** [comment]
Looks like an entity name conflict, enable specificEntityNames in the config and try it again.  When I created this mod I was under the impression entity names were sandboxed under the mod, but they are not :( ... so I added that config option.
