### ISSUE TITLE
Hotbar Transparency Glitch

### ISSUE THREAD

**Issue by kenijey** [ToroCraft/ToroQuest#150]
please help it :( my hotbar loses it's transparency when i get close to the village and get the info GUI on the top-right corner on the screen. thanks..
![glitch](https://cloud.githubusercontent.com/assets/24831406/26194015/a650b57e-3bbf-11e7-9a87-eb28ad1ea0ef.gif)

**Comment by frodare** [comment]
If you upload a copy of the hotbar mod, I should have some time to take a look at it and see if there is something in TQ I can patch to fix this problem.  Not much I can do without it though.

**Comment by kenijey** [comment]
it's a part of my resource pack, i can upload it with only-hotbar included. 
https://drive.google.com/open?id=0B6b0yPfoStOGT1FudFF4aUtxRlE
here it is, you can use it as a resource pack, then get closer to a village (get the tq village gui) then the glitch will happen. (tested on mc 1.11.2, forge 2298)

**Comment by frodare** [comment]
Thanks, that is what I needed to debug the problem.

**Comment by frodare** [comment]
ToroQuest 1.11.2-3.5 is now deployed with a fix for this issue.

**Comment by kenijey** [comment]
thank you! it works awesome

**Comment by Hypsandar** [comment]
a
