### ISSUE TITLE
[i18n] Number variables when there are not only one

### ISSUE THREAD

**Issue by Snownee** [ToroCraft/ToroQuest#152]
Hello! I'm translating ToroQuest into Chinese, but the problem is that the word order in Chinese is often different from that in English. So I often get a headache translating words such as *Welcome back to %s of %s*.

I hope the variables could be numbered (for example: %s1), so that I can introduce this awesome mod to my Chinese friends ASAP : )

**Comment by frodare** [comment]
That does sound like a headache! So you need a way to change the order? I certainly hope that is possible, I will look through forge docs to find out.  Those lines are not currently used, but it would still be nice to have them translated so that they can be in the future.

**Comment by Snownee** [comment]
Thanks a lot!

**Comment by frodare** [comment]
It looks like it uses the builtin `java.lang.String format` method so you should be able to use:

`%1$s` and `%2$s` 

This was a helpful reference: https://stackoverflow.com/questions/1915074/understanding-the-in-javas-format-strings
