### ISSUE TITLE
ooh, crashed when placing a block

### ISSUE THREAD

**Issue by AugiteSoul** [ToroCraft/ToroQuest#153]
augitesite.ddns.net/mc_crashes/crash-2017-05-31_21.09.52-server.txt

**Comment by frodare** [comment]
Looks like the crash is actually happening here:
`lumien.randomthings.handler.AsmHandler.postSlipFix(AsmHandler.java:455)`

**Comment by frodare** [comment]
If I get time I am going to install that mod and try to see why TQ is giving it some heart burn.  Does it crash every time you place any block?

**Comment by AugiteSoul** [comment]
No. The first time it crashed (with not even a crashreport, I'll bring the logs soon) was because of a Reccurent Complex structure generated.

**Comment by frodare** [comment]
@AugiteSoul was this issue ever figured out?

**Comment by Hypsandar** [comment]
Yeah, the game crashes when you place a block from another mod, i thought this was a forge issue, not TQ but what do i know.

**Comment by Hypsandar** [comment]
It doesnt happen every time, its rather random.

**Comment by frodare** [comment]
@Hypsandar do you have Random Things installed?  Also, please post the crash report here.  It might have something useful.

**Comment by Hypsandar** [comment]
"---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  offlineskins (OfflineSkins-1.12-v1.jar)
  ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 6/29/17 9:42 PM
Description: Unexpected error

SplashProgress has detected a error loading Minecraft.
This can sometimes be caused by bad video drivers.
We have automatically disabled the new Splash Screen in config/splash.properties.
Try reloading minecraft before reporting any errors.
net.minecraftforge.fml.client.SplashProgress$4: java.lang.IllegalStateException: Splash thread
	at net.minecraftforge.fml.client.SplashProgress.disableSplash(SplashProgress.java:672)
	at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:664)
	at net.minecraftforge.fml.client.FMLClientHandler.haltGame(FMLClientHandler.java:318)
	at xaero.common.minimap.MinimapInterface.drawInterface(MinimapInterface.java:97)
	at xaero.common.interfaces.InterfaceHandler.drawInterfaces(InterfaceHandler.java:54)
	at xaero.common.events.Events.drawPre(Events.java:76)
	at xaero.common.events.Events.renderPre(Events.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_181_Events_renderPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:181)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:885)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:322)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:140)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1089)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Splash thread
	at net.minecraftforge.fml.client.SplashProgress.checkThreadState(SplashProgress.java:597)
	at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:652)
	... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.client.SplashProgress.disableSplash(SplashProgress.java:672)
	at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:664)
	at net.minecraftforge.fml.client.FMLClientHandler.haltGame(FMLClientHandler.java:318)
	at xaero.common.minimap.MinimapInterface.drawInterface(MinimapInterface.java:97)
	at xaero.common.interfaces.InterfaceHandler.drawInterfaces(InterfaceHandler.java:54)
	at xaero.common.events.Events.drawPre(Events.java:76)
	at xaero.common.events.Events.renderPre(Events.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_181_Events_renderPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:181)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:885)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:322)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:140)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Hypsandar'/322, l='MpServer', x=244.98, y=64.00, z=-471.88]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-228,64,100), Chunk: (at 12,4,4 in -15,6; contains blocks -240,0,96 to -225,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 116753 game time, 22135 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 94 total; [EntityItem['item.item.arrow'/35591, l='MpServer', x=301.03, y=68.00, z=-536.17], EntitySkeleton['Skeleton'/35849, l='MpServer', x=312.46, y=64.00, z=-424.68], EntityBat['Bat'/36111, l='MpServer', x=286.50, y=31.74, z=-496.99], EntityVillager['Villager'/273, l='MpServer', x=202.70, y=62.55, z=-500.50], EntityVillager['Villager'/274, l='MpServer', x=233.44, y=63.94, z=-503.89], EntityVillager['Villager'/275, l='MpServer', x=225.33, y=63.00, z=-500.50], EntityVillager['Villager'/277, l='MpServer', x=225.62, y=64.00, z=-502.30], EntityGuard['Guard'/278, l='MpServer', x=249.45, y=73.00, z=-465.48], EntitySentry['Sentry'/35095, l='MpServer', x=281.49, y=70.00, z=-441.29], EntityVillager['Villager'/281, l='MpServer', x=208.55, y=64.00, z=-473.32], EntityVillager['Villager'/282, l='MpServer', x=227.30, y=64.00, z=-481.72], EntityMinecartChest['Minecart with Chest'/284, l='MpServer', x=207.50, y=16.06, z=-493.50], EntityMinecartChest['Minecart with Chest'/285, l='MpServer', x=193.50, y=28.06, z=-486.50], EntityVillager['Villager'/290, l='MpServer', x=193.53, y=66.00, z=-494.39], EntityGuard['Guard'/295, l='MpServer', x=217.50, y=67.56, z=-525.60], EntityGuard['Guard'/296, l='MpServer', x=220.69, y=67.55, z=-523.52], EntityArmorStand['Armor Stand'/297, l='MpServer', x=224.50, y=67.00, z=-525.50], EntityArmorStand['Armor Stand'/298, l='MpServer', x=224.50, y=67.00, z=-524.50], EntityArmorStand['Armor Stand'/299, l='MpServer', x=224.50, y=67.00, z=-522.50], EntityArmorStand['Armor Stand'/300, l='MpServer', x=224.50, y=67.00, z=-521.50], EntityArmorStand['Armor Stand'/301, l='MpServer', x=224.50, y=67.00, z=-525.50], EntityArmorStand['Armor Stand'/302, l='MpServer', x=224.50, y=67.00, z=-524.50], EntityArmorStand['Armor Stand'/303, l='MpServer', x=224.50, y=67.00, z=-522.50], EntityArmorStand['Armor Stand'/304, l='MpServer', x=224.50, y=67.00, z=-521.50], EntityArmorStand['Armor Stand'/305, l='MpServer', x=224.50, y=67.00, z=-525.50], EntityArmorStand['Armor Stand'/306, l='MpServer', x=224.50, y=67.00, z=-524.50], EntityArmorStand['Armor Stand'/307, l='MpServer', x=224.50, y=67.00, z=-522.50], EntityArmorStand['Armor Stand'/308, l='MpServer', x=224.50, y=67.00, z=-521.50], EntityArmorStand['Armor Stand'/309, l='MpServer', x=224.50, y=67.00, z=-525.50], EntityArmorStand['Armor Stand'/310, l='MpServer', x=224.50, y=67.00, z=-524.50], EntityArmorStand['Armor Stand'/311, l='MpServer', x=224.50, y=67.00, z=-522.50], EntityArmorStand['Armor Stand'/312, l='MpServer', x=224.50, y=67.00, z=-521.50], EntityGuard['Guard'/313, l='MpServer', x=232.35, y=78.00, z=-523.34], EntityGuard['Guard'/314, l='MpServer', x=224.32, y=71.00, z=-523.42], EntityGuard['Guard'/315, l='MpServer', x=225.51, y=67.00, z=-523.50], EntitySentry['Sentry'/35387, l='MpServer', x=234.70, y=64.00, z=-501.67], EntitySentry['Sentry'/35388, l='MpServer', x=234.03, y=64.00, z=-501.37], EntityVillager['Villager'/317, l='MpServer', x=208.50, y=66.00, z=-464.29], EntityBat['Bat'/36157, l='MpServer', x=314.42, y=30.10, z=-529.58], EntityBat['Bat'/36158, l='MpServer', x=307.49, y=44.22, z=-527.44], EntityVillager['Villager'/319, l='MpServer', x=229.70, y=62.94, z=-501.36], EntityGuard['Guard'/320, l='MpServer', x=233.59, y=74.00, z=-484.52], EntityVillager['Villager'/321, l='MpServer', x=224.70, y=62.20, z=-500.51], EntityVillager['Villager'/324, l='MpServer', x=229.71, y=64.00, z=-504.06], EntitySentry['Sentry'/36168, l='MpServer', x=272.50, y=60.00, z=-505.50], EntitySentry['Sentry'/36169, l='MpServer', x=272.50, y=60.00, z=-505.50], EntityCreeper['Creeper'/35423, l='MpServer', x=239.81, y=64.00, z=-476.51], EntityVillager['Villager'/359, l='MpServer', x=225.52, y=64.00, z=-503.08], EntitySentry['Sentry'/35692, l='MpServer', x=200.29, y=63.00, z=-489.73], EntityMinecartChest['Minecart with Chest'/365, l='MpServer', x=179.50, y=27.06, z=-474.50], EntityItem['item.item.string'/35193, l='MpServer', x=187.66, y=67.00, z=-488.63], EntityItem['item.item.ma.crafting_inferium_essence'/35194, l='MpServer', x=188.69, y=67.00, z=-489.21], EntityBat['Bat'/36225, l='MpServer', x=256.82, y=58.03, z=-510.41], EntityBat['Bat'/34439, l='MpServer', x=269.49, y=61.10, z=-489.75], EntityBat['Bat'/34443, l='MpServer', x=245.20, y=56.10, z=-480.59], EntitySentry['Sentry'/36235, l='MpServer', x=264.64, y=70.00, z=-445.50], EntitySentry['Sentry'/36236, l='MpServer', x=265.60, y=70.00, z=-445.51], EntitySentry['Sentry'/36237, l='MpServer', x=271.29, y=71.00, z=-448.20], EntityBat['Bat'/36241, l='MpServer', x=318.73, y=31.08, z=-512.08], EntityBat['Bat'/36242, l='MpServer', x=323.57, y=30.07, z=-514.30], EntityItem['item.item.arrow'/35220, l='MpServer', x=301.88, y=66.00, z=-503.34], EntityItem['item.item.bone'/35221, l='MpServer', x=301.88, y=66.00, z=-503.27], EntityItem['item.item.ma.crafting_inferium_essence'/35222, l='MpServer', x=301.73, y=66.00, z=-502.92], EntitySentry['Sentry'/33179, l='MpServer', x=261.30, y=64.00, z=-470.54], EntityShopkeeper['Shopkeeper'/415, l='MpServer', x=242.61, y=64.56, z=-496.52], EntityBat['Bat'/36003, l='MpServer', x=283.70, y=63.64, z=-491.48], EntityItem['item.item.rottenFlesh'/35749, l='MpServer', x=203.75, y=63.00, z=-492.81], EntityItem['item.item.ma.crafting_inferium_essence'/35750, l='MpServer', x=203.75, y=64.00, z=-493.16], EntityGuard['Guard'/429, l='MpServer', x=290.55, y=66.00, z=-547.79], EntityGuard['Guard'/431, l='MpServer', x=252.54, y=67.00, z=-547.27], EntityItem['item.item.rottenFlesh'/35763, l='MpServer', x=199.02, y=60.00, z=-511.17], EntityGuard['Guard'/437, l='MpServer', x=267.64, y=78.00, z=-474.51], EntityVillageLord['Village Lord'/438, l='MpServer', x=261.50, y=70.00, z=-476.50], EntityGuard['Guard'/439, l='MpServer', x=258.39, y=78.00, z=-474.51], EntityGuard['Guard'/440, l='MpServer', x=266.81, y=70.00, z=-480.36], EntityGuard['Guard'/442, l='MpServer', x=275.91, y=69.00, z=-545.13], EntityGuard['Guard'/443, l='MpServer', x=256.42, y=74.00, z=-480.44], EntitySentry['Sentry'/36028, l='MpServer', x=302.19, y=70.00, z=-472.94], EntityItem['item.item.string'/35266, l='MpServer', x=241.36, y=66.00, z=-512.07], EntityGuard['Guard'/450, l='MpServer', x=256.51, y=69.00, z=-538.10], EntityItem['item.item.ma.crafting_inferium_essence'/35267, l='MpServer', x=241.42, y=66.00, z=-510.99], EntityGuard['Guard'/451, l='MpServer', x=254.31, y=66.00, z=-550.50], EntityBat['Bat'/36039, l='MpServer', x=223.13, y=26.10, z=-463.25], EntityGuard['Guard'/456, l='MpServer', x=268.38, y=78.50, z=-481.54], EntityGuard['Guard'/457, l='MpServer', x=251.74, y=65.00, z=-533.29], EntityGuard['Guard'/458, l='MpServer', x=259.45, y=78.00, z=-480.46], EntityGuard['Guard'/459, l='MpServer', x=277.32, y=70.00, z=-540.49], EntityGuard['Guard'/460, l='MpServer', x=282.70, y=69.00, z=-540.49], EntityItem['item.item.ma.crafting_inferium_essence'/35542, l='MpServer', x=280.96, y=62.00, z=-488.73], EntitySentry['Sentry'/35544, l='MpServer', x=251.23, y=64.00, z=-474.67], EntityPlayerSP['Hypsandar'/322, l='MpServer', x=244.98, y=64.00, z=-471.88], EntityItem['item.item.rottenFlesh'/35835, l='MpServer', x=201.89, y=61.00, z=-489.23], EntityItem['item.item.ma.crafting_inferium_essence'/35836, l='MpServer', x=201.09, y=63.00, z=-489.92], EntityItem['item.item.rottenFlesh'/35839, l='MpServer', x=244.16, y=66.00, z=-513.18]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2732)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 208180816 bytes (198 MB) / 981180416 bytes (935 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.40 Powered by Forge 14.21.0.2382 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.0.2382.jar) 
	UCHIJAAAA	forge{14.21.0.2382} [Minecraft Forge] (forge-1.12-14.21.0.2382.jar) 
	UCHIJAAAA	ColorUtility{1.0.4} [ColorUtility] (minecraft.jar) 
	UCHIJAAAA	additionalbanners{1.5.37} [Additional Banners] (AdditionalBanners-1.12-1.5.37.jar) 
	UCHIJAAAA	ambience{GRADLE:VERSION-GRADLE:BUILD} [Ambience] (Ambience 1.1-9.jar) 
	UCHIJAAAA	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UCHIJAAAA	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.12-1.5.1.jar) 
	UCHIJAAAA	endercrop{1.12-1.3.4} [Ender Crop] (endercrop-1.12-1.3.4.jar) 
	UCHIJAAAA	jei{4.7.0.68} [Just Enough Items] (jei_1.12-4.7.0.68.jar) 
	UCHIJAAAA	menubooks{1.0.1} [Menu Books] (menubooks-1.0.1..jar) 
	UCHIJAAAA	metamorph{1.1.3} [Metamorph] (metamorph-1.1.3-1.12.jar) 
	UCHIJAAAA	minecolonies{1.12-0.8.2947} [MineColonies] (minecolonies-universal-1.12-0.8.2947.jar) 
	UCHIJAAAA	mysticalagriculture{1.6.0} [Mystical Agriculture] (mysticalagriculture[1.12]-1.6.0.jar) 
	UCHIJAAAA	neat{1.4-15} [Neat] (Neat 1.4-15.jar) 
	UCHIJAAAA	notenoughwands{1.5.7} [Not Enough Wands] (notenoughwands-1.12-1.5.7.jar) 
	UCHIJAAAA	offlineskins{1.12-v1} [OfflineSkins] (OfflineSkins-1.12-v1.jar) 
	UCHIJAAAA	personalcars{1.3} [Personal Cars] (PersonalCars-1.3.jar) 
	UCHIJAAAA	simpleleather{1.12-1.0} [Simple Leather] (simpleleather-1.12-1.0.jar) 
	UCHIJAAAA	toroquest{1.11.2-5.0} [ToroQuest] (toroquest-1.12-5.0.jar) 
	UCHIJAAAA	traverse{1.2.1} [Traverse] (Traverse-1.12-1.2.1-22..jar) 
	UCHIJAAAA	waddles{0.5.2} [Waddles] (Waddles-1.12-0.5.2.jar) 
	UCHIJAAAA	waystones{4.0.5} [Waystones] (Waystones_1.12-4.0.5..jar) 
	UCHIJAAAA	wholetreeaxe{1.7.1} [Whole Tree Axe] (WholeTreeAxe-1.12-1.7.1.jar) 
	UCHIJAAAA	xaerominimap{1.13.1} [Xaero's Minimap] (Xaeros_Minimap_1.13.1_Forge_1.12.jar) 
	UCHIJAAAA	xaeroworldmap{1.9} [Xaero's World Map] (XaerosWorldMap_b1.9_Forge_1.12.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
offlineskins (OfflineSkins-1.12-v1.jar)
  lain.mods.skins.asm.ASMTransformer
ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
  com.Axeryok.ColorUtility.ColorUtilityTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 369.09' Renderer: 'GeForce 920M/PCIe/SSE2'
	Launched Version: 1.12-forge1.12-14.21.0.2382
	LWJGL: 2.9.4
	OpenGL: GeForce 920M/PCIe/SSE2 GL version 4.5.0 NVIDIA 369.09, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz"

I don't have random things, as the matter of fact it doesn't work for me, the game wont run with it.

I placed a Biblio craft block: Oak table

**Comment by Hypsandar** [comment]
Well, sorry for the wall of text.. There's no spoilers in this text editor...

**Comment by Hypsandar** [comment]
Frodare, are you the dev? Have i been talking to **you** on Minecraft.curseforge.com?

**Comment by frodare** [comment]
Yup, that was me. No problem with the text, that doesn't bother me at all.  

That crash looks like it occurred on startup possibly caused by Xaero's Minimap. Are you sure that was the one created when you were placing a block?

**Comment by Hypsandar** [comment]
Ah, so Frodare... Tell me, where did your beard go? How could you shave that beautiful universe? Do you know how many mico medieval creatures you have slain? Darn it, i am dissapointed.
------------------------
I'm 100% sure unless the crash log wasn't created, it was the latest on in the "crash logs" folder.
