### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Bjarka1** [ToroCraft/ToroQuest#154]
I love TQ and what it do to MC. However, I now have a problem, it won't let me start with TQ installed.
Here is the crash report [https://pastebin.com/wcxTQQwR](url)

**Comment by frodare** [comment]
Looks like an entity name conflict, enable specificEntityNames in the config and try it again.  When I created this mod I was under the impression entity names were sandboxed under the mod, but they are not :( ... so I added that config option.

Thanks for posting your issue, and that positive support!
