### ISSUE TITLE
Provinces overlap

### ISSUE THREAD

**Issue by NekoAmps** [ToroCraft/ToroQuest#156]
If two villages are near enough to each other, their provinces will overlap. I've seen this occur out of luck or because generation variables were changed (through Mo' Villages, in my case). The rep badge displays only one of the provinces, and it may get stuck on that province if the player travels through a chain of overlapping territories. The badge disappears as expected when the player moves into unclaimed territory.

I really like the idea of multiple villages forming a single province if near enough to each other. This is what I thought was happening at first, but seeing the badge change depending on how I traveled into a village and checking the guards' capes showed me that this isn't the case. I also like the idea of provinces having disputed territories between them, though not quite as much.

ToroQuest version: 3.5
For Minecraft version: 1.11.2
Forge version: 1.11.2-13.20.0.2315

**Comment by frodare** [comment]
If two provinces overlap, they are suppose to merge.  This one might be a bit tough to reproduce, but I will give it a shot when I start working on this mod again.  Thanks for letting me know!

**Comment by NekoAmps** [comment]
Thank you for the quick response! 😸 I look forward to this being figured out.

I checked to see if I could reproduce this issue in Flatlands with the village(distance=9) parameter, and I could. In the below screenshots, I am not in Xafadina, as shown by the capes. However, the badge is displaying for Xafadina in the first shot because I just came from that province.
![2017-06-12_00 02 33](https://user-images.githubusercontent.com/8448825/27022466-f9671824-4f02-11e7-96e2-6cc321a9a296.png)

Here, I entered this village from a different direction and the badge is now displaying correctly.
![2017-06-12_00 04 23](https://user-images.githubusercontent.com/8448825/27022467-f9675a82-4f02-11e7-8c5c-01765fbaebad.png)

I believe I saw examples of provinces properly including multiple villages, so that is probably working in some if not most cases.

**Comment by frodare** [comment]
This is perfect. Thanks for find a way to reproduce this issue, it will same me a lot of time!  I will not be able to work on this for a week while I am traveling, but I will look into when I get back.

**Comment by NekoAmps** [comment]
Happy I can help. Safe travels!

**Comment by frodare** [comment]
This looks to be more complicated then I was hoping. I think the capes and GUI are actually correct, however, when a new village spawns next to another there is a chance it can overwrite some of the boundary of the first.

I am going to push a fix for the until after the 1.12 update, which means 1.11.2 and before will have this bug.

**Comment by NekoAmps** [comment]
Sounds good. It's not like this bug is game-breaking, after all. Just a bit confusing. Thanks for your work on this!
