### ISSUE TITLE
[1.11.2-3.5] Battle of the Mods (vs Mowzie's Mobs)

### ISSUE THREAD

**Issue by kreezxil** [ToroCraft/ToroQuest#157]
A new mod entered the ring the other day called Mowzie's Mobs, it adds hostile tribesmen to the Savannah biomes. I had a player start a base at Village in this biome type and upon return to his village lord he says some tribesmen spawned near him and began trying to kill him. He said he fought them off, killing them one by one and as he did so his rep plummeted. 

I think the mobs in question inherit form the Villager class which would in essence make your mod think they are neutrals not worthy of death.

message thread: https://minecraft.curseforge.com/projects/colonial-expansion?comment=119

**Comment by frodare** [comment]
That sounds like a cool mod. I will look into adding a config option or something to handle custom mobs.  Or, maybe just ignore them for simplicity.

**Comment by kreezxil** [comment]
Maybe have it automatically ignore anything other than your mobs and pure
vanilla passives. Add a config to allow custom passives. That way I could
add "Fire and Ice" mod to a pack and declare that the dragons in it are the
gods of the world and therefore killing them in a village Will drop the rep
by configurable amount.

**Comment by frodare** [comment]
For the time being the only real change I made was to check if exact class was `net.minecraft.entity.passive.EntityVillager` which should fix the root problem.  I am going to wait on the more advanced config options.
