### ISSUE TITLE
[1.11.2-3.5] Feeding & Breeding or Yet Another Battle of the Mods

### ISSUE THREAD

**Issue by kreezxil** [ToroCraft/ToroQuest#163]
It was brought to my attention that the Toros won't breed with other cows and that does seem quite odd.

Comment made by a player of my Colonial Exploration modpack, this will likely come up in my  Colonial Expansion modpack as both have the same mods:

> I was having some problems with this modpack.  I had a bunch of cows around me so I decided to try to set up a **cow farm.**  Unfortunately I soon discovered that while the cows were animania cows, **all the bulls were toroquest 'toros' which didn't seem to use the same AI.**  In addition, the animania cows were failing to eat or drink from the trough.  All they'd do is stand around being hungry and thirsty.  There seems to be some problems there.  I couldn't breed cows if I wanted to and I can't really do anything with the cows I have except kill them (assuming the hordes of toros don't finish me off first)

**Comment by frodare** [comment]
The main problem I see here is the Toro spawning mechanism.  We had some issues getting the Toros to be generated in world creation so we decided to add a chance of them spawning when cows spawn.  I am going to look into fixing the Toro spawning, maybe I will be able to figure it out this time ;)
