### ISSUE TITLE
[1.12] Some GL State is leaking.

### ISSUE THREAD

**Issue by Shadows-of-Fire** [ToroCraft/ToroQuest#165]
When a toroquest rep overlay is drawn, text is rendered behind items in the hotbar.
[![Screenshot from Gyazo](https://gyazo.com/12c348e619665eb859d42c3a12a8e4f2/raw)](https://gyazo.com/12c348e619665eb859d42c3a12a8e4f2)  
Sounds like someone forgot to push/pop a gl matrix somewhere.

**Comment by zeriley** [comment]
That was exactly the problem, thanks.  Saved me some research.  Will be fixed in next release.

**Comment by zeriley** [comment]
Fixed in 1.12-5.2, available now on curseforge
