### ISSUE TITLE
Crashes when Guards atack other monster [1.12]

### ISSUE THREAD

**Issue by NoplixDE** [ToroCraft/ToroQuest#167]
So I was playing/testing my modpack, and stumble over a problem.
Whenever Villager Guards (don't now the name of them) attack "[FakeOres] < Mod (https://minecraft.curseforge.com/projects/fake-ores2)" monster, it crashes.

Crash Report: https://gist.github.com/NoplixDE/a5a2e3e2e1064d901bae6a339959c7a3

It could be also FakeOres mod fault but at this point, I don't know. 

Regards, Noplix

**Comment by frodare** [comment]
The bug is in FakeOres.  If anything besides a player kills an ore entity, the game will crash:

I have reported the issue there: https://github.com/elias54/Fake-Ores-2/issues/5

**Comment by NoplixDE** [comment]
Thanks for letting me know!
