### ISSUE TITLE
Update the ToroQuest NPC skins?

### ISSUE THREAD

**Issue by Hypsandar** [ToroCraft/ToroQuest#171]
They all use the same skin, come on.. 😝 
I'm good at making MC skins, let me know if i can help.

**Comment by frodare** [comment]
Help with the textures would be greatly appreciated!  Just keep in mind the group will have to decide if they should be included in the mod, and possibly as for changes to be made.

If you are interested in contributing, create a pull request to add guard textures here: https://github.com/ToroCraft/ToroQuest/tree/master/resources/assets/toroquest/textures/entity/guard

**Comment by frodare** [comment]
The guard texture is also used for the Village Lord and Sentries!

**Comment by AugiteSoul** [comment]
Gonna see if I can make new skins. To add even more variety, skin parts could be swapped, to make unique entities.

**Comment by Hypsandar** [comment]
Hmm, since there's 6 factions.. Maybe have all the guard textures differently for each faction? Instead of the same texture but with a different mark/logo?
Maybe a whole different outfit style/color.
-------------
I might make a few textures, but no promises.. I thought this was using a casual Minecraft player skin texturing which i have prepped a program for which wont work for this, though there's always JPSp.

**Comment by frodare** [comment]
If you ignore the cape part, the top left of the texture should be standard.

**Comment by AugiteSoul** [comment]
reply to Hypsandar:

Or more chances to have specific NBT depending on the faction.

**Comment by NekoAmps** [comment]
Regarding Augite's thoughts on NBT, I don't think a gender tag is really necessary. Torsos, especially in armor, don't need to be feminized (boobified, I mostly mean).
But if you are going to throw in feminized torsos, then a tag for facial hair would be nice. Bearded ladies are lovely ladies all the same, but I feel like if it wasn't a limited possibility then players would consider them to be erroneous occurrence rather than a feature.

**Comment by Rutes** [comment]
If you could collaborate with this guy, it would be a dream come true...
http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/wip-mods/2850564-the-villager-soldiers-mod

**Comment by frodare** [comment]
@Rutes that looks pretty cool, if I get back in to MC modding that looks like it would be a fun project.
