### ISSUE TITLE
Reset Reputation

### ISSUE THREAD

**Issue by Truzedo** [ToroCraft/ToroQuest#174]
How can I reset one specific players reputation with a certain lord?  Right now this -150 in rep and is being killed on site?  Is there anything I can do to help them?

**Comment by frodare** [comment]
If you are OP, the command is something like /tq req PLAYERNAME REPAMOUNT, tab completion should work.  You might need to be logged in as a player opposed to running it from the server, I don't remember.

**Comment by Truzedo** [comment]
OK still getting this message when i try that for the player.    "Usage: commands.tq.usage"  Tap completion does not appear to be doing anything either.  Can you please be more specific?  I really appreciate the help.

**Comment by frodare** [comment]
Oh, bummer.  It only works for the currently logged in player.  You would have to OP them and have them run `/tq rep 0`.

**Comment by Truzedo** [comment]
Yeah now it says Usage: commands.tq.not_in_civ

**Comment by frodare** [comment]
Lol, you will have to /tp him into the civ that he has bad rep in. Make
sure you tp to a safe house or something.

**Comment by Truzedo** [comment]
ok great.  Thanks!
