### ISSUE TITLE
Ticking Sentry crashes the game

### ISSUE THREAD

**Issue by Darkmega18** [ToroCraft/ToroQuest#178]
[crash-2017-08-29_19.07.03-server.txt](https://github.com/ToroCraft/ToroQuest/files/1259835/crash-2017-08-29_19.07.03-server.txt)
Because the entity being ticked was yours, I submit this to you. However it also references better survival modweaponhandler, so I'll possibly be bringing this over there too...

This crashed off screen, but it happened when I was chatting with a minecraft comes alive villager within one of your villages. There were sentries hanging about doing guard duty etc and I was about to give a gift to a villager when it crashed.

unrelated, it could also be scaling health trying to modify the sentry's health and damage possibly and doing something wrong, but I can't be sure.

**Comment by frodare** [comment]
This does appear to be a better survival bug.  That looks like a closed source project, so it's hard for me to know for sure.

**Comment by Darkmega18** [comment]
Roger. I reported it to the maker via PM, so I'll find out in time. but I had a feeling it would be more related possibly to a wierd enchantment or buff from better survival or scaling health than from directly on the sentries. Since they were just guilty of spawning all over the place cause I was in the village's area of influence.

**Comment by frodare** [comment]
Yeah. I won't be surprised if there is something in the sentry code I can change to fix this bug, it's just hard for me to track it down because I don't have the code that triggered the issue. Hopefully mujmajnkraft will either fix it on his side or point me in the right direction in the sentry code.

**Comment by Darkmega18** [comment]
I'll pass on the issue link then so you can possibly figure it out together. :)

**Comment by Darkmega18** [comment]
ok, yeah, confirmed it was better survival. I took it out and found the ticking sentry that was perma-crashing stopped crashing.
