### ISSUE TITLE
Is it possible to move Village buildings?

### ISSUE THREAD

**Issue by ChellieH** [ToroCraft/ToroQuest#179]
I was testing some village transformations on a creative world and built a new keep and guard tower in better locations (definitely still in the province) but when I destroyed the original keep the Village Lord just stood in the spot where the keep used to be and the guards dispersed to the barracks. 

Is there a way to move buildings or create new buildings that the villagers will recognise or do I have to work around the positions they spawn in?

**Comment by frodare** [comment]
Currently guards sentries and village lords do not have affiliation with the structures they are on or in.  They are simply spawned there.  You could move the village lord with water or possibly a minecart to a different location, as long as it is in the boundaries of the civilization.
