### ISSUE TITLE
Enabling Rep Badge?

### ISSUE THREAD

**Issue by Sheanar** [ToroCraft/ToroQuest#180]
As part of a mod pack (Sprout) a different mod's HUD ended up where the Rep info would be. I've managed to hide that ...but the rep still isn't visible (even standing in a town). Is there a command to re-enable the rep badge?

Idea: Add a physical, optional badge for packs to use where there are too many HUDs? XD 

You've got a great mod - just trying not to anger any villagers and I wasn't sure where else to ask. Thanks!

**Comment by GrimPanda** [comment]
You can change it's position in the config file for it.  Sprout has it 19000 pixels to the right off the screen, change that value to wherever you want it.

**Comment by Sheanar** [comment]
Thank you. I was able to get it working! Much appreciated.
