### ISSUE TITLE
Please update tp 1.12.2

### ISSUE THREAD

**Issue by SabylRose** [ToroCraft/ToroQuest#185]
I would love to add this mod to my modpack but even though it says the last update should work with the 1.12.2 it is causing crashes when talking to the lords or villiagers

**Comment by Rutes** [comment]
It's working fine for me in 1.12.2
I have it in my modpack and running pretty well on my server too:
https://minecraft.curseforge.com/projects/less-tech-more-dragon

**Comment by SabylRose** [comment]
Perhaps then it isn't playing well with something else. Thank you for looking into it.

**Comment by frodare** [comment]
1.12.2 version is now curse
