### ISSUE TITLE
I don't understand a quest 

### ISSUE THREAD

**Issue by DarkBladeSider** [ToroCraft/ToroQuest#186]
Hi i don't understand the quest :"clear vagabond encampment " the npc tell me: " location 701 meters at -428.876" i don't understand where i need to go to complete .I'll try to add a screen.
![2018-01-01_17 17 12](https://user-images.githubusercontent.com/35004962/34469102-dd5badec-ef17-11e7-938a-1fc0da98c81c.png)
![2018-01-01_17 17 12](https://user-images.githubusercontent.com/35004962/34469118-3560a9de-ef18-11e7-8a00-5e17eb313a78.png)

I'm sorry for my bad english but i hope you'll understand me .

**Comment by Gorehid** [comment]
It looks like it is saying that x: -428 and z: 876 is where the Vagabond encampment is.
