### ISSUE TITLE
Quest [Lord] Doesn't Recognize Items.

### ISSUE THREAD

**Issue by EpicBlake** [ToroCraft/ToroQuest#190]
After playing for 2 hours with the mod, and abandoning every quests because the Lord doesn't recognize the items, I got frustrated and stopped playing.
The Lord in every quests doesn't seem to recognize specific items.
I can only complete mob killing quests.
https://imgur.com/vDRf1mM
https://imgur.com/EkyDiAH

**Comment by Mijithemidge** [comment]
I have had this problem too. He gave me a pickaxe and told me to mine 16 blocks of coal ore in the region. Done, and when I try to turn it in, he says I'm 16 blocks short. It's right there! Is a mod causing the number on coal ore to change so he no longer recognizes it? Or does he see something like all coal ores and is just bugged?

**Comment by frodare** [comment]
Duplicate: https://github.com/ToroCraft/ToroQuest/issues/133
