### ISSUE TITLE
Aggro by AI

### ISSUE THREAD

**Issue by HangYourself** [ToroCraft/ToroQuest#192]
Hi there, 

Started a few construction near a village, including crops. My crops were ready to be harvested so I harvested them. Got attacked by a sentinel, then another and another tirelessly.
It's now impossible for me to play as every I revive I get knocked out by those sentinels. It's unbearable, how can I stay in my own village if always attacked by sentinels ?

**Comment by frodare** [comment]
You can reset your rep, look here for reference: https://github.com/ToroCraft/ToroQuest/issues/174.  In the server config there are some settings that change affect rep that you might want to change.
