### ISSUE TITLE
Suggestion: The Ability to configure currency (for modpacks)

### ISSUE THREAD

**Issue by ClockwerkKaiser** [ToroCraft/ToroQuest#195]
Hey all! 

I'm absolutely LOVING this mod, and I'm kicking myself for not giving it a chance sooner. I absolutely adore the reputation and questing systems, and I've been building a small modpack for friends using ToroQuest as one of the main mods. 

However, one thing requested of me for the pack was to add a currency system using coins. (I'm currently using the ordinary coins mod... but the mod choice itself isn't important). The only mod in the pack I can't add any coin interaction/usage to is ToroQuest. 

So, my feature suggestion is to add a config option to change the mod's currency (for quests, and trades). 

Alternatively, the ability to change it in craft/modtweaker would also be welcome.

**Comment by frodare** [comment]
Thanks for the kind words! This request might be a tough one to implement, so it probably won't happen. The next time I am working on this project I will take a look to see if I can think of any ideas to make using different money schemes possible, that would be a neat feature.
