### ISSUE TITLE
Enchanted Book bought from a shopkeeper won't apply to anything

### ISSUE THREAD

**Issue by Febilian** [ToroCraft/ToroQuest#198]
A player on my server reported that an enchanted book bought from a ToroQuest villager doesn't apply to a valid tool(in this case, an unenchanted diamond pickaxe). Using a book from the creative menu as a test _did_ work, so then I had the player use the crafttweaker command on currently held items to check the NBT on both books. This is what I got:

Shop's version:
`<minecraft:enchanted_book>.withTag({ench: [{lvl: 1 as short, id: 33}]})`

Creative menu version(this one works):
`<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 33}]})`

The NBT data format seems to be different between them.

ToroQuest version: 5.2

Let me know if I can provide more info that might help.

**Comment by frodare** [comment]
Thanks @Febilian! I have made a patch and uploaded it to curse for review.  I hope it will fix the issue, if not let me know.

**Comment by Febilian** [comment]
Wow, that was fast! I'll give it a try in the next day or so. Thanks!
