### ISSUE TITLE
Sugerir mejora del toro

### ISSUE THREAD

**Issue by ghiltonT** [ToroCraft/ToroQuest#199]
Pensaba que seria genial si el toro procreara con la vacas un ejemplo seria como el gallo en el mod hatchery donde se habre una interfas y se le deja semilla y el solo las procrea, me parece genial que el toro defienda a la vacas ayuda a mejorar una granja de vacas pero me gustaria que no solo fuera eso que el toro procree con las vacas y si hay mas toros que se peleen para hacerlo mas real

**Comment by frodare** [comment]
We have had ideas like that in the past, but we try pretty not to alter the vanilla Minecraft mechanics, so it would still be important for us that the cow mechanics stay unchanged. The closest we got to implementing a feature like this was proposed here, https://github.com/ToroCraft/ToroQuest/issues/21, but it was never picked up.
