### ISSUE TITLE
sentrys spawns

### ISSUE THREAD

**Issue by TheDCPlaya** [ToroCraft/ToroQuest#200]
can we get a config line to modify the spawn rate on the sentrys please im using the mod in a pack and they are taking over the spawns for the whole pack

**Comment by Thethuthinnang** [comment]
I second this. They're a cool feature to the mod, but it'd be nice to be able to modify the spawn rate.

**Comment by Wing01** [comment]
Spawn rate will be configurable in the next update. Setting the spawn rate to 0 will disable sentrys from spawning. Will work on modifying spawn location and scan radius in the near future
