### ISSUE TITLE
extra villiager spawns?

### ISSUE THREAD

**Issue by Thesmartone7** [ToroCraft/ToroQuest#201]
i have minecraft comes alive and this mod and if this mod is making more villagers spawn, id rather that not happen and was wondering if a config could be added to turn that off, however i have a lot of mods and this mod may not be doing that, if so, I apologize and feel free to close this issue.

**Comment by frodare** [comment]
This mod shouldn't be spawning in more villagers.  It does spawn in a set number of other entities on generation and then keeps spawning sentry entities (too many sentries, but that is already filed as a bug).  Good luck hunting it down!

**Comment by Thesmartone7** [comment]
so uh....i took it out and made a new world and...maybe it has something to do with my other mods(minecraft comes alive, iblis, etc.) but it does seem to connect to torocraft as the in the new world without torocraft the bug doesn't happen...however i have combined mca and toro before and they worked fine, the only mod that was changed or added was tinkers and base,modern metals, ill ask the metals people whats up but i doubt it was them.

**Comment by frodare** [comment]
That's very strange. You should try TQ by itself and see if the problem exists.

**Comment by Thesmartone7** [comment]
i am very confused how but dynamic trees and its addons were the issue....somehow...as removing them made all the mods play nice again and alone toro didnt have the bug so it wasnt yall sorry for the bother, the only thing i could think of is me and my 106 mods made minecraft think just a little too hard and made some strange bugs occur, great mod btw real nice.
