### ISSUE TITLE
Sentry Attacking?

### ISSUE THREAD

**Issue by BladedBiscuit** [ToroCraft/ToroQuest#202]
Ive started too build my own civilization and the sentrys spawned in, one night i accidentally hit one when i was killing a zombie, now, if i stand in one spot too long, a couple of the sentrys will start too attack me for no reason, and they wont stop attacking until i kill them, then more spawn in and it just repeats, i dont know if this is supposed too happen or not?

**Comment by Wing01** [comment]
From issue #200, you will be able to set the spawn rate to 0 in the next update to prevent more from spawning.
