### ISSUE TITLE
Add custom and better equipment to shopkeepers

### ISSUE THREAD

**Issue by zeriley** [ToroCraft/ToroQuest#24]
- Cursed weapons/armor for Moon
      - we could create a bunch of weapons/armor/enchantments that have side effects, like extra sharpness at the cost of durability, get poisoned when attacking, more protection but decreases max hp, etc.
      -  I think we should not display what the effects are. It always just shows Cursed Sword or whatever, then you have to use it to figure out the benefits and drawbacks

Special Custom Items For Civilizations:

Wind: Mage Staff?
Earth: Toro Armor
Fire: Glass Sword
Moon: Royal Armor
Sun: Samurai Armor
Water: ?

**Comment by frodare** [comment]
I need help coming up with a list of items. Each item needs:
- a name
- the civ it is sold from
- the rep level needed to buy the item
- price (up to two stacks of whatever)
- an explanation of what it is (example: a stone pickaxe with fortune I)

**Comment by frodare** [comment]
We should add API support so other mods can add items to sell.

**Comment by zeriley** [comment]
- Pickaxe of Greed
      - Moon
      - Friend
      - 10 emeralds (?) or 5 emeralds and 20 nether quartz
      - an iron pickaxe that when mining diamonds will either drop three diamonds or a chunk of coal

- Sword of Pain
      - Moon
      - Friend
      - 10 emeralds (?) or 5 emeralds and 20 nether quartz
      - an iron sword which does 12 points of damage to an unarmored enemy and 3 points of damage to the user

I kind of like the idea of nether materials being traded in for the cursed gear

**Comment by CawCawDrakon** [comment]
Juggernaut Armor
- Terra
- Hero
- 30 Obsidian and 7 Emeralds
- Twice as effective as diamond armor, but slows you down as if you were sneaking across soul sand

Soup of the Heavens
- Gustaberg
- Friend
- 12 emeralds, 6 gold ingots, 3 blaze powder, and a block of dirt
- Restores 6 Hunger. That´s it. This is just soup. Nothing but some overpriced soup. 
(Which I would frame and put on a wall. Obviously.)

Witch´s symbol
- Terra
- Ally
- Some potions?
- A runestone. Having this in your inventory makes witches not attack you.

Wreath of the Wrathful Sun
- Solaris
- Hero
- 10 Gold ingots and 4 blaze rods
- A helmet that, if you go below half your life, sends fireballs flying in random directions

**Comment by zeriley** [comment]
We'd have to figure out the right balance of slowing down for the juggernaut armor.  A full set would slow you down to the slowest speed, and each piece needs to slow you down a fraction of that slowest speed.  I like the idea, though.  Witch's Symbol may be hard to implement.  Depends on what kind of Forge hooks exist for altering the vanilla mob AI.

**Comment by CawCawDrakon** [comment]
Another two ideas:

Lover's Heel
- Solaris
- Friend
- 1 golden Apple
- Boots that give you a life and strength boost. Armor value of leather. Can only be taken Off in the End 

Spicy grilled chicken
- Lumens
- Friend
- 4 Emeralds and 1 raw chicken
- Sets you on fire, but gives you two minutes of fire Resistance. Otherwisr like normal grilled chicken

**Comment by frodare** [comment]
LOL, I like where this going.

**Comment by CawCawDrakon** [comment]
Armor of the Atoner 
- Aquarius 
- Hero 
- Something then Guardians Drop? Sorry, forgot
- Completely negates meelee damage. Explodes when Hit by a projectile

**Comment by frodare** [comment]
http://minecraft.gamepedia.com/Prismarine_Shard?

**Comment by CawCawDrakon** [comment]
These Items could be another gameplay effect for the lorebooks: Only there you can find more details about the Items, the wiki only saying that there are drawbacks to powerful items

**Comment by CawCawDrakon** [comment]
Ah, so maybe10 dark prismarine for the atoner
