### ISSUE TITLE
Make Mage Tower more rare

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroQuest#6]

**Comment by zeriley** [comment]
We had talked about changing this to only possibly generating every intersection of 1000 and 1000, roughly.  We could look into implementing that, or just continue to change the probability as it currently is done.

**Comment by zeriley** [comment]
I copied the algorithm for the nether fortress for spawning.  I searched for quite a while in a real world and never found one.  We may need to make it less rare now, but I kind of like there not being many.  However, if we keep it where there are very few, we should raise the minimum number of floors.
