### ISSUE TITLE
Lord Gooey

### ISSUE THREAD

**Issue by zeriley** [ToroCraft/ToroQuest#67]
The room has slime Spawners
And the slimes are designed to walk to him
And he eats them and gains strength and health
So you have to kill the slimes
Or kite him away to buy yourself extra time

**Comment by pandapaul** [comment]
omgeez I love this idea @zeriley

**Comment by NotAVerb** [comment]
It would be neat if this structure could be tied to slime chunks. That way the slime chunks would be even more valuable, without this new slime dungeon upsetting vanillas quirkiness if the player thinks such a thing is desirable.
Such a limitation should probably also be toggleable via the config if it were to be implemented.
