### ISSUE TITLE
Civilization Reputation 

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroQuest#8]
- Grain reputation by:
- [ ] Trading with villagers
- [x] Killing mobs withing a set radius of the village
- Lose reputation by:
- [x] Killing a villager
- [ ] Gaining reputation with another civilization

**Comment by zeriley** [comment]
For losing reputation by gaining reputation with another civilization, I think an easy implementation of that would be using the Village Lord trophy (which would drop just like mob bosses will drop).  If you turn that in to other Village Lords you get as much rep as you lose for killing the Lord.  However, if you turn it into the rival village, you'll get double rep.

<=> indicates rivalries
Sun <=> Moon
Water <=> Fire
Earth <=> Wind
