### ISSUE TITLE
Player preview in the inventory view is inverted when in a province

### ISSUE THREAD

**Issue by scigeotech** [ToroCraft/ToroQuest#89]
i'm using the 1.11.2 version. this bug only happened in my survival world (and i spawned very near a village)

http://imgur.com/a/ymSS8

here are my mods that i'm using:
Appleskin
Optifine
CreeperChicks (creeper chickens, not creeper people)
FoodExpansion
JEI
Neat
Pam's Get All the Seeds!
Toroquest

**Comment by frodare** [comment]
LOL, we blindly assumed that was a forge 1.11+ bug this whole time. I will look into fixing it tonight.  It was annoying the crap out of me too!
