### ISSUE TITLE
Create Civilization Banners

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroQuest#9]
Banners should be displayed on the village Keep

**Comment by zeriley** [comment]
I know we had an issue with displaying these using the block mapper.  Maybe we could just place them in front of the entrances stuck in the ground to simplify things.

**Comment by frodare** [comment]
that wasn't the problem. I think it was hacking into the village creation to figure out where the roads end. To simplify this we could just hang them on the keep for now.  and many put them in the barracks.

**Comment by zeriley** [comment]
I meant entrances of the keep.  I thought placing them on the walls was difficult
