### ISSUE TITLE
Recipes don't work for JEI

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroQuest#90]
recipes won't work for jei. can you fix them?
~kenijey

https://minecraft.curseforge.com/projects/toroquest?comment=10

**Comment by kenijey** [comment]
yeah i meant this thing

**Comment by frodare** [comment]
I should have thought of this earlier, but I don't think TQ adds any craftable items.  The items must be obtained from the shopkeeper except for the Royal Armor which currently only drops randomly when a village lord is killed.

**Comment by kenijey** [comment]
yeah but when you killed a toro, u got toro leather. and pressing U on it, no recipe uses :D something should be craftable with toro leather man. it should be, believe me xD

**Comment by frodare** [comment]
Currently the only use for toro leather is trading with shopkeepers for special items.

**Comment by kenijey** [comment]
you should increase the spawn rate of toro structures. it is really hard to find them

**Comment by frodare** [comment]
Agreed.  I think we should add a configuration option for how common they are.

**Comment by kenijey** [comment]
yes

**Comment by frodare** [comment]
I forgot to mention, I created a new issue for this: https://github.com/ToroCraft/ToroQuest/issues/93
