### ISSUE TITLE
Add a configuration option for how common structures generate

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroQuest#93]

**Comment by zeriley** [comment]
Would be nice if we decreased the value of loot based on frequency.  If frequency < x, then give better loot; frequency > x, give worse loot

**Comment by frodare** [comment]
I like that idea. We would have to start using our own loot system though.  Wouldn't be difficult but would take some work.

**Comment by zeriley** [comment]
Also, this should be a server option, right?  Probably obvious, but I wanted to clarify for whomever picks this task up.
