### ISSUE TITLE
Game Crash (optifine compability)

### ISSUE THREAD

**Issue by kenijey** [ToroCraft/ToroQuest#96]
i'm getting this crash when coming toroquest village... i solved it with deleting optifine... it's all about connected textures. please fix it
[crash-2017-01-20_21.35.52-client.txt](https://github.com/ToroCraft/ToroQuest/files/720264/crash-2017-01-20_21.35.52-client.txt)

**Comment by zeriley** [comment]
This looks like it's coming from harvestcraft

**Comment by frodare** [comment]
Agreed, it does appear to come from harvestcraft.  Maybe it is compiled for a different version of MC?  If you can check with them and let us know.

**Comment by kenijey** [comment]
oh really... sorry then...

**Comment by frodare** [comment]
I am going to go ahead and close this issue.  If it does turn out that TQ is causing this crash somehow, please let us know.

**Comment by kenijey** [comment]
okay, of course. thanks.
